-------------------------------------------------------------------
GRANT ALL ON TABLE ${schema}.carrello TO ${schema};
GRANT ALL ON TABLE ${schema}.cd_info_pagamento TO ${schema};
GRANT ALL ON TABLE ${schema}.idempotency_cache TO ${schema};
GRANT ALL ON TABLE ${schema}.messaggi TO ${schema};
GRANT ALL ON TABLE ${schema}.pm_metadata TO ${schema};
GRANT ALL ON TABLE ${schema}.pm_session_data TO ${schema};
GRANT ALL ON TABLE ${schema}.position_activate TO ${schema};
GRANT ALL ON TABLE ${schema}.position_payment TO ${schema};
GRANT ALL ON TABLE ${schema}.position_payment_plan TO ${schema};
GRANT ALL ON TABLE ${schema}.position_payment_status TO ${schema};
GRANT ALL ON TABLE ${schema}.position_payment_status_snapshot TO ${schema};
GRANT ALL ON TABLE ${schema}.position_receipt TO ${schema};
GRANT ALL ON TABLE ${schema}.position_receipt_recipient TO ${schema};
GRANT ALL ON TABLE ${schema}.position_receipt_recipient_status TO ${schema};
GRANT ALL ON TABLE ${schema}.position_receipt_transfer TO ${schema};
GRANT ALL ON TABLE ${schema}.position_receipt_xml TO ${schema};
GRANT ALL ON TABLE ${schema}.position_retry_pa_send_rt TO ${schema};
GRANT ALL ON TABLE ${schema}.position_retry_sendpaymentresult TO ${schema};
GRANT ALL ON TABLE ${schema}.position_service TO ${schema};
GRANT ALL ON TABLE ${schema}.position_status TO ${schema};
GRANT ALL ON TABLE ${schema}.position_status_snapshot TO ${schema};
GRANT ALL ON TABLE ${schema}.position_subject TO ${schema};
GRANT ALL ON TABLE ${schema}.position_transfer TO ${schema};
GRANT ALL ON TABLE ${schema}.retry_pa_attiva_rpt TO ${schema};
GRANT ALL ON TABLE ${schema}.retry_pa_invia_rt TO ${schema};
GRANT ALL ON TABLE ${schema}.retry_rpt TO ${schema};
GRANT ALL ON TABLE ${schema}.rpt TO ${schema};
GRANT ALL ON TABLE ${schema}.rpt_activations TO ${schema};
GRANT ALL ON TABLE ${schema}.rpt_soggetti TO ${schema};
GRANT ALL ON TABLE ${schema}.rpt_versamenti TO ${schema};
GRANT ALL ON TABLE ${schema}.rpt_versamenti_bollo TO ${schema};
GRANT ALL ON TABLE ${schema}.rpt_xml TO ${schema};
GRANT ALL ON TABLE ${schema}.rt TO ${schema};
GRANT ALL ON TABLE ${schema}.rt_versamenti TO ${schema};
GRANT ALL ON TABLE ${schema}.rt_versamenti_bollo TO ${schema};
GRANT ALL ON TABLE ${schema}.rt_xml TO ${schema};
GRANT ALL ON TABLE ${schema}.stati_carrello TO ${schema};
GRANT ALL ON TABLE ${schema}.stati_carrello_snapshot TO ${schema};
GRANT ALL ON TABLE ${schema}.stati_rpt TO ${schema};
GRANT ALL ON TABLE ${schema}.stati_rpt_snapshot TO ${schema};
GRANT ALL ON TABLE ${schema}.token_utility TO ${schema};
GRANT ALL ON TABLE ${schema}.verifica_bollettino TO ${schema};
-------------------------------------------------------------------
ALTER TABLE IF EXISTS ${schema}.carrello OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.cd_info_pagamento OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.idempotency_cache OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.messaggi OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.pm_metadata OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.pm_session_data OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.position_activate OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.position_payment OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.position_payment_plan OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.position_payment_status OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.position_payment_status_snapshot OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.position_receipt OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.position_receipt_recipient OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.position_receipt_recipient_status OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.position_receipt_transfer OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.position_receipt_xml OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.position_retry_pa_send_rt OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.position_retry_sendpaymentresult OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.position_service OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.position_status OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.position_status_snapshot OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.position_subject OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.position_transfer OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.retry_pa_attiva_rpt OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.retry_pa_invia_rt OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.retry_rpt OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.rpt OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.rpt_activations OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.rpt_soggetti OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.rpt_versamenti OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.rpt_versamenti_bollo OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.rpt_xml OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.rt OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.rt_versamenti OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.rt_versamenti_bollo OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.rt_xml OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.stati_carrello OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.stati_carrello_snapshot OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.stati_rpt OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.stati_rpt_snapshot OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.token_utility OWNER to ${schema};
ALTER TABLE IF EXISTS ${schema}.verifica_bollettino OWNER to ${schema};
-------------------------------------------------------------------
