{
 "title": "[GLOBAL] - Activate senza SPO Copy - with filters",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Intermediario_psp",
    "query": "INTERMEDIARI_PSP\n| extend variable = strcat(ID_INTERMEDIARIO_PSP,\"|\",INTERMEDIARIO_DESCR)\n| extend v = strcat(ID_INTERMEDIARIO_PSP, \" : \", INTERMEDIARIO_DESCR)\n| sort by INTERMEDIARIO_DESCR asc\n| project variable"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Totale activatePaymentNotice",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to));\nlet totalActivate = ReEvent\n| where insertedTimestamp between (start .. end)\n| project-away payload\n| where tipoEvento == \"activatePaymentNotice\"\n| where categoriaEvento == \"INTERFACCIA\"\n| where sottoTipoEvento == \"RESP\";\nlet activateFailed = FAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento == \"activatePaymentNotice\";\nlet activateOk = \ntotalActivate\n| join kind=leftouter activateFailed on idDominio, iuv, ccp, uniqueId\n| where isnull(insertedTimestamp1);\nlet totalSpo = ReEvent\n| where insertedTimestamp between (start .. end)\n| project-away payload\n| where tipoEvento == \"sendPaymentOutcome\"\n| where categoriaEvento == \"INTERFACCIA\"\n| where sottoTipoEvento == \"REQ\";\nactivateOk\n| join kind=leftouter totalSpo on idDominio, iuv, ccp\n| project insertedTimestamp, tipoEvento, idDominio, iuv, ccp, stazione, canale, psp, sessionId, tipoEvento2, tipoEvento1\n| summarize Totale=count() by tipoEvento, tipoEvento2\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Totale SPO",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "SPO Mancanti",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "PSP che non inviano SPO",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to));\nlet totalActivate = ReEvent\n| where insertedTimestamp between (start .. end)\n| project-away payload\n| where tipoEvento == \"activatePaymentNotice\"\n| where categoriaEvento == \"INTERFACCIA\"\n| where sottoTipoEvento == \"RESP\";\nlet activateFailed = FAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento == \"activatePaymentNotice\";\nlet activateOk = \ntotalActivate\n| join kind=leftouter activateFailed on idDominio, iuv, ccp, uniqueId\n| where isnull(insertedTimestamp1);\nlet totalSpo = ReEvent\n| where insertedTimestamp between (start .. end)\n| project-away payload\n| where tipoEvento == \"sendPaymentOutcome\"\n| where categoriaEvento == \"INTERFACCIA\"\n| where sottoTipoEvento == \"REQ\";\nactivateOk\n| join kind=leftouter totalSpo on idDominio, iuv, ccp\n| project insertedTimestamp, tipoEvento, idDominio, iuv, ccp, stazione, canale, psp, sessionId, tipoEvento2, tipoEvento1\n| where isempty(tipoEvento2)\n| extend intPSP = substring(canale, 0, strlen(canale)-3)\n| join kind=inner INTERMEDIARI_PSP on $left.intPSP == $right.ID_INTERMEDIARIO_PSP",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "PA Impattate",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to));\nlet totalActivate = ReEvent\n| where insertedTimestamp between (start .. end)\n| project-away payload\n| where tipoEvento == \"activatePaymentNotice\"\n| where categoriaEvento == \"INTERFACCIA\"\n| where sottoTipoEvento == \"RESP\";\nlet activateFailed = FAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento == \"activatePaymentNotice\";\nlet activateOk = \ntotalActivate\n| join kind=leftouter activateFailed on idDominio, iuv, ccp, uniqueId\n| where isnull(insertedTimestamp1);\nlet totalSpo = ReEvent\n| where insertedTimestamp between (start .. end)\n| project-away payload\n| where tipoEvento == \"sendPaymentOutcome\"\n| where categoriaEvento == \"INTERFACCIA\"\n| where sottoTipoEvento == \"REQ\";\nactivateOk\n| join kind=leftouter totalSpo on idDominio, iuv, ccp\n| project insertedTimestamp, tipoEvento, idDominio, iuv, ccp, stazione, canale, psp, sessionId, tipoEvento2, tipoEvento1\n| where isempty(tipoEvento2)\n| extend intPSP = substring(canale, 0, strlen(canale)-3)\n| join kind=inner INTERMEDIARI_PSP on $left.intPSP == $right.ID_INTERMEDIARIO_PSP\n| join kind=inner PA on $left.idDominio == $right.ID_DOMINIO",
     "querySource": "raw"
    }
   ]
  }
 ]
}