{
 "title": "Annulli Nodo",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Attivazioni Totali (activatePaymentNotice, activatePaymentNoticeV2)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nlet _cancelPayment = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento == \"mod3CancelV2\"\n| summarize min(insertedTimestamp) by paymentToken\n| project paymentToken, min_insertedTimestamp;\nlet _activate = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"activatePaymentNotice\",\"activatePaymentNoticeV2\")\n| where sottoTipoEvento == \"REQ\"\n| extend expiration = extract(\"<expirationTime>([0-9]+)\", 1, base64_decode_tostring(payload))\n| extend expiration = case(isempty(expiration), \"1800000\", expiration)\n| extend expirationDate = datetime_add(\"millisecond\", toint(expiration), insertedTimestamp)\n| where isempty(paymentToken) == false\n| project insertedTimestamp, expiration, paymentToken, expirationDate, psp;\nlet _spo = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"sendPaymentOutcome\", \"sendPaymentOutcomeV2\")\n| where sottoTipoEvento == \"REQ\"\n| project DATA_SPO=insertedTimestamp, paymentToken;\n// in questa query , ogni riga contiene le informazioni di attivazione, sendPaymentOutcome, data di cancellazione prevista, data di cancellazione passata\n// quelli che hanno la DATA_SPO vanno ignorati\n_activate\n| join kind=leftouter _cancelPayment on paymentToken\n| join kind=leftouter _spo on paymentToken\n| project DATA_ATTIVAZIONE=insertedTimestamp, DURATA_TOKEN_MS=expiration, TOKEN=paymentToken, DATA_SCADENZA_PREVISTA=expirationDate, DATA_CANCELLAZIONE=min_insertedTimestamp, PSP=psp, DATA_SPO\n| extend DIFFERENZA_SCADENZA=tostring(toint((DATA_CANCELLAZIONE - DATA_SCADENZA_PREVISTA) / time(1ms)))\n| extend DIFFERENZA_ACT_SPO=tostring(toint((DATA_SPO - DATA_ATTIVAZIONE) / time(1ms)))\n| summarize TOTALE=count() ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Attivazioni concluse con una SPO",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nlet _cancelPayment = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento == \"mod3CancelV2\"\n| summarize min(insertedTimestamp) by paymentToken\n| project paymentToken, min_insertedTimestamp;\nlet _activate = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"activatePaymentNotice\",\"activatePaymentNoticeV2\")\n| where sottoTipoEvento == \"REQ\"\n| extend expiration = extract(\"<expirationTime>([0-9]+)\", 1, base64_decode_tostring(payload))\n| extend expiration = case(isempty(expiration), \"1800000\", expiration)\n| extend expirationDate = datetime_add(\"millisecond\", toint(expiration), insertedTimestamp)\n| where isempty(paymentToken) == false\n| project insertedTimestamp, expiration, paymentToken, expirationDate, psp;\nlet _spo = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"sendPaymentOutcome\", \"sendPaymentOutcomeV2\")\n| where sottoTipoEvento == \"REQ\"\n| project DATA_SPO=insertedTimestamp, paymentToken;\n// in questa query , ogni riga contiene le informazioni di attivazione, sendPaymentOutcome, data di cancellazione prevista, data di cancellazione passata\n// quelli che hanno la DATA_SPO vanno ignorati\n_activate\n| join kind=leftouter _cancelPayment on paymentToken\n| join kind=leftouter _spo on paymentToken\n| where isempty(DATA_SPO) == false\n| project DATA_ATTIVAZIONE=insertedTimestamp, DURATA_TOKEN_MS=expiration, TOKEN=paymentToken, DATA_SCADENZA_PREVISTA=expirationDate, DATA_CANCELLAZIONE=min_insertedTimestamp, PSP=psp, DATA_SPO\n| extend DIFFERENZA_SCADENZA=tostring(toint((DATA_CANCELLAZIONE - DATA_SCADENZA_PREVISTA) / time(1ms)))\n| extend DIFFERENZA_ACT_SPO=tostring(toint((DATA_SPO - DATA_ATTIVAZIONE) / time(1ms)))\n| summarize TOTALE=count() ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Attivazioni concluse con mod3Cancel",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nlet _cancelPayment = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento == \"mod3CancelV2\"\n| summarize min(insertedTimestamp) by paymentToken\n| project paymentToken, min_insertedTimestamp;\nlet _activate = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"activatePaymentNotice\",\"activatePaymentNoticeV2\")\n| where sottoTipoEvento == \"REQ\"\n| extend expiration = extract(\"<expirationTime>([0-9]+)\", 1, base64_decode_tostring(payload))\n| extend expiration = case(isempty(expiration), \"1800000\", expiration)\n| extend expirationDate = datetime_add(\"millisecond\", toint(expiration), insertedTimestamp)\n| where isempty(paymentToken) == false\n| project insertedTimestamp, expiration, paymentToken, expirationDate, psp;\nlet _spo = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"sendPaymentOutcome\", \"sendPaymentOutcomeV2\")\n| where sottoTipoEvento == \"REQ\"\n| project DATA_SPO=insertedTimestamp, paymentToken;\n// in questa query , ogni riga contiene le informazioni di attivazione, sendPaymentOutcome, data di cancellazione prevista, data di cancellazione passata\n// quelli che hanno la DATA_SPO vanno ignorati\n_activate\n| join kind=leftouter _cancelPayment on paymentToken\n| join kind=leftouter _spo on paymentToken\n| project DATA_ATTIVAZIONE=insertedTimestamp, DURATA_TOKEN_MS=expiration, TOKEN=paymentToken, DATA_SCADENZA_PREVISTA=expirationDate, DATA_CANCELLAZIONE=min_insertedTimestamp, PSP=psp, DATA_SPO\n| extend DIFFERENZA_SCADENZA=tostring(toint((DATA_CANCELLAZIONE - DATA_SCADENZA_PREVISTA) / time(1ms)))\n| extend DIFFERENZA_ACT_SPO=tostring(toint((DATA_SPO - DATA_ATTIVAZIONE) / time(1ms)))\n| where isempty(DATA_CANCELLAZIONE) == false\n| summarize TOTALE=count() ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Attivazioni in attesa di ESITO",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nlet _cancelPayment = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento == \"mod3CancelV2\"\n| summarize min(insertedTimestamp) by paymentToken\n| project paymentToken, min_insertedTimestamp;\nlet _activate = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"activatePaymentNotice\",\"activatePaymentNoticeV2\")\n| where sottoTipoEvento == \"REQ\"\n| extend expiration = extract(\"<expirationTime>([0-9]+)\", 1, base64_decode_tostring(payload))\n| extend expiration = case(isempty(expiration), \"1800000\", expiration)\n| extend expirationDate = datetime_add(\"millisecond\", toint(expiration), insertedTimestamp)\n| where isempty(paymentToken) == false\n| project insertedTimestamp, expiration, paymentToken, expirationDate, psp;\nlet _spo = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"sendPaymentOutcome\", \"sendPaymentOutcomeV2\")\n| where sottoTipoEvento == \"REQ\"\n| project DATA_SPO=insertedTimestamp, paymentToken;\n// in questa query , ogni riga contiene le informazioni di attivazione, sendPaymentOutcome, data di cancellazione prevista, data di cancellazione passata\n// quelli che hanno la DATA_SPO vanno ignorati\n_activate\n| join kind=leftouter _cancelPayment on paymentToken\n| join kind=leftouter _spo on paymentToken\n| project DATA_ATTIVAZIONE=insertedTimestamp, DURATA_TOKEN_MS=expiration, TOKEN=paymentToken, DATA_SCADENZA_PREVISTA=expirationDate, DATA_CANCELLAZIONE=min_insertedTimestamp, PSP=psp, DATA_SPO\n| extend DIFFERENZA_SCADENZA=tostring(toint((DATA_CANCELLAZIONE - DATA_SCADENZA_PREVISTA) / time(1ms)))\n| extend DIFFERENZA_ACT_SPO=tostring(toint((DATA_SPO - DATA_ATTIVAZIONE) / time(1ms)))\n| where isempty(DATA_CANCELLAZIONE) == false\n| where isempty(DATA_SPO) == false\n| summarize TOTALE=count() ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Quanto impiega il nodo a cancellare in base alla durata della sessione",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nlet _cancelPayment = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento == \"mod3CancelV2\"\n| summarize min(insertedTimestamp) by paymentToken\n| project paymentToken, min_insertedTimestamp;\nlet _activate = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"activatePaymentNotice\",\"activatePaymentNoticeV2\")\n| where sottoTipoEvento == \"REQ\"\n| extend expiration = extract(\"<expirationTime>([0-9]+)\", 1, base64_decode_tostring(payload))\n| extend expiration = case(isempty(expiration), \"1800000\", expiration)\n| extend expirationDate = datetime_add(\"millisecond\", toint(expiration), insertedTimestamp)\n| where isempty(paymentToken) == false\n| project insertedTimestamp, expiration, paymentToken, expirationDate, psp;\nlet _spo = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"sendPaymentOutcome\", \"sendPaymentOutcomeV2\")\n| where sottoTipoEvento == \"REQ\"\n| project DATA_SPO=insertedTimestamp, paymentToken;\n// in questa query , ogni riga contiene le informazioni di attivazione, sendPaymentOutcome, data di cancellazione prevista, data di cancellazione passata\n// quelli che hanno la DATA_SPO vanno ignorati\n_activate\n| join kind=leftouter _cancelPayment on paymentToken\n| join kind=leftouter _spo on paymentToken\n| project DATA_ATTIVAZIONE=insertedTimestamp, DURATA_TOKEN_MS=expiration, TOKEN=paymentToken, DATA_SCADENZA_PREVISTA=expirationDate, DATA_CANCELLAZIONE=min_insertedTimestamp, PSP=psp, DATA_SPO\n| extend DIFFERENZA_SCADENZA=tostring(toint((DATA_CANCELLAZIONE - DATA_SCADENZA_PREVISTA) / time(1ms)))\n| extend DIFFERENZA_ACT_SPO=tostring(toint((DATA_SPO - DATA_ATTIVAZIONE) / time(1ms)))\n| where isempty(DATA_SPO)\n| where isempty(DATA_CANCELLAZIONE) == false\n| extend DIFFERENZA_SCADENZA = (toint(DIFFERENZA_SCADENZA) / 1000)\n| project DIFFERENZA_SCADENZA\n| summarize count() by bin(DIFFERENZA_SCADENZA, 60)\n| extend DIFFERENZA_SCADENZA = DIFFERENZA_SCADENZA / 60\n| project-rename TOTALE=count_\n| extend DIFFERENZA_SCADENZA=strcat(tostring(DIFFERENZA_SCADENZA),' minuti')",
     "querySource": "raw"
    }
   ]
  }
 ]
}