{
 "title": "[CONFIG] - PSP Associazioni Canali",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Intermediario",
    "query": {
     "query": "INTERMEDIARI_PSP\n| extend variable = strcat(ID_INTERMEDIARIO_PSP,\"|(\",ID_INTERMEDIARIO_PSP,\") \",INTERMEDIARIO_DESCR)\n| extend v = strcat(ID_INTERMEDIARIO_PSP, \" : \", INTERMEDIARIO_DESCR)\n| sort by INTERMEDIARIO_DESCR asc\n| project variable"
    }
   },
   {
    "name": "Canale",
    "query": {
     "query": "PT_REL_PSP\n| where ID_INTERMEDIARIO == $Intermediario\n| extend v = strcat(CANALE, \"|\", CANALE)\n| sort by CANALE asc\n| project v"
    }
   },
   {
    "name": "psp",
    "label": "PSP",
    "query": {
     "query": "PSP\n| where ENABLED == \"Y\"\n| extend l = strcat(ID_PSP,\"|\", \"(\", ID_PSP,\") \", RAGIONE_SOCIALE)\n| project l"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Intermediari PSP presenti sul nodo",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "INTERMEDIARI_PSP\n| where ENABLED == \"Y\"\n| summarize TOTALE=count()",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Percentuale di intermediazioni presenti sul nodo",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "PT_REL_PSP\n| summarize TOTALE=count() by INTERMEDIARIO_DESCR\n| sort by TOTALE desc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Dettaglio Intermediazione - $Intermediario",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Numero di intermediazioni per ogni canale",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "PT_REL_PSP\n| where ID_INTERMEDIARIO == $Intermediario\n| summarize TOTALE=count() by CANALE",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Intermediati da $Intermediario",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "PT_REL_PSP\n| where ID_INTERMEDIARIO == $Intermediario\n| where CANALE in ($Canale)\n| extend PSP_DESCR=case(isempty(PSP_DESCR), PSP_RAGIONE_SOCIALE, PSP_DESCR)\n| project-rename PSP=PSP_DESCR\n| project PSP, ID_PSP, CANALE\n| sort by PSP asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Dettaglio",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "PT_REL_PSP\n| where ID_INTERMEDIARIO in ($Intermediario)\n| where CANALE == $Canale",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Dettaglio $psp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Dettaglio $psp",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "PT_REL_PSP\n| where ID_PSP == $psp",
     "querySource": "raw"
    }
   ]
  }
 ]
}