{
 "title": "[GLOBAL] - Errori emessi dal NODO verso i PSP",
 "description": "Errori PPT_* forniti alle chiamate dei PSP",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "PSP",
    "query": {
     "query": "PSP\n| where ENABLED == \"Y\"\n| extend DESCRIZIONE=case(isempty(DESCRIZIONE), RAGIONE_SOCIALE, DESCRIZIONE)\n| extend v = strcat(ID_PSP, \"|(\", ID_PSP, \") \", DESCRIZIONE)\n| sort by DESCRIZIONE asc \n| project v"
    }
   },
   {
    "name": "FAULTCODE",
    "query": {
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"activatePaymentNotice\",\"verifyPaymentNotice\",\"sendPaymentOutcome\", \"sendPaymentOutcomeV2\", \"nodoInviaRT\", \"nodoAttivaRPT\", \"nodoVerificaRPT\", \"activatePaymentNoticeV2\", \"activateIOPayment\")\n| where faultCode != \"PPT_MULTI_BENEFICIARIO\"\n| where faultCode startswith \"PPT_\"\n| distinct faultCode\n| sort by faultCode asc"
    }
   }
  ]
 },
 "panels": [
  { "title": "NODO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Errori emessi dal NODO",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"activatePaymentNotice\",\"verifyPaymentNotice\",\"sendPaymentOutcome\", \"sendPaymentOutcomeV2\", \"nodoInviaRT\", \"nodoAttivaRPT\", \"nodoVerificaRPT\", \"activatePaymentNoticeV2\", \"activateIOPayment\", \"verificaBollettino\")\n| where faultCode != \"PPT_MULTI_BENEFICIARIO\"\n| where faultCode startswith \"PPT_\"\n| summarize NUMERO_EVENTI=count() by faultCode\n| sort by NUMERO_EVENTI desc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Distribuzione $FAULTCODE",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"activatePaymentNotice\",\"verifyPaymentNotice\",\"sendPaymentOutcome\", \"sendPaymentOutcomeV2\", \"nodoInviaRT\", \"nodoAttivaRPT\", \"nodoVerificaRPT\", \"activatePaymentNoticeV2\", \"activateIOPayment\", \"verificaBollettino\")\n| where faultCode startswith \"PPT_\"\n| where faultCode == $FAULTCODE\n| summarize NUMERO_EVENTI=count() by psp\n| join kind=inner PSP on $left.psp == $right.ID_PSP\n| extend DESCRIZIONE=case(isempty(DESCRIZIONE), RAGIONE_SOCIALE, DESCRIZIONE)\n| extend DESCRIZIONE=case(ID_PSP==\"AGID_01\", \"Touchpoint pagoPA\", DESCRIZIONE)\n| project psp, NUMERO_EVENTI\n| sort by NUMERO_EVENTI desc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Distribuzione nel tempo di $FAULTCODE",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 16, "x": 8, "y": 15 },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nlet diff_in_seconds=datetime_diff('second', end, start);\nlet _step = case(\ndiff_in_seconds between (0 .. 60), 1s, // con un range di un minuto, step di un secondo\ndiff_in_seconds between (61 .. 3600), 1m, // con un range di un'ora, step di 1 minuto\ndiff_in_seconds between (3601 .. 10800), 15m, // con un range che va da 1h a 3h, step di 15m\ndiff_in_seconds between (10801 .. 21600), 30m, // con un range che va da 3h a 6h, step di 30m\ndiff_in_seconds between (21601 .. 86399), 1h, // con un range che va da 6h a 24h, step di 1h\ndiff_in_seconds > 86399, 1d, // con un range che va dalle 24h, step di 1d\n1d\n);\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"activatePaymentNotice\",\"verifyPaymentNotice\",\"sendPaymentOutcome\", \"sendPaymentOutcomeV2\", \"nodoInviaRT\", \"nodoAttivaRPT\", \"nodoVerificaRPT\", \"activatePaymentNoticeV2\", \"activateIOPayment\", \"verificaBollettino\")\n| where faultCode == $FAULTCODE\n| summarize NUMERO_EVENTI=count() by bin(insertedTimestamp, 1h)\n| extend insertedTimestamp = datetime_local_to_utc(insertedTimestamp, \"Europe/Rome\")\n| sort by NUMERO_EVENTI desc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Distribuzione $FAULTCODE",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"activatePaymentNotice\",\"verifyPaymentNotice\",\"sendPaymentOutcome\", \"sendPaymentOutcomeV2\", \"nodoInviaRT\", \"nodoAttivaRPT\", \"nodoVerificaRPT\", \"activatePaymentNoticeV2\", \"activateIOPayment\", \"verificaBollettino\")\n| where faultCode startswith \"PPT_\"\n| where faultCode == $FAULTCODE\n| summarize NUMERO_EVENTI=count() by tipoEvento\n| sort by NUMERO_EVENTI desc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Dettaglio $FAULTCODE su tutti i PSP",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"activatePaymentNotice\",\"verifyPaymentNotice\",\"sendPaymentOutcome\", \"sendPaymentOutcomeV2\", \"nodoInviaRT\", \"nodoAttivaRPT\", \"nodoVerificaRPT\", \"activatePaymentNoticeV2\", \"activateIOPayment\", \"verificaBollettino\")\n| where faultCode == $FAULTCODE\n| extend insertedTimestamp = datetime_local_to_utc(insertedTimestamp, \"Europe/Rome\")\n| project insertedTimestamp, tipoEvento, idDominio, iuv, ccp, psp, stazione, canale, faultCode, faultDescription, sessionId\n",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Dettaglio $PSP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Errori emessi dal NODO a $PSP",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"activatePaymentNotice\",\"verifyPaymentNotice\",\"sendPaymentOutcome\", \"sendPaymentOutcomeV2\", \"nodoInviaRT\", \"nodoAttivaRPT\", \"nodoVerificaRPT\", \"verificaBollettino\")\n| where faultCode != \"PPT_MULTI_BENEFICIARIO\"\n| where faultCode startswith \"PPT_\"\n| where psp == $PSP\n| summarize NUMERO_EVENTI=count() by faultCode\n| sort by NUMERO_EVENTI desc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Distribuzione $FAULTCODE per $PSP sui metodi",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"activatePaymentNotice\",\"verifyPaymentNotice\",\"sendPaymentOutcome\", \"sendPaymentOutcomeV2\", \"nodoInviaRT\", \"nodoAttivaRPT\", \"nodoVerificaRPT\", \"verificaBollettino\")\n| where faultCode == $FAULTCODE\n| where psp == $PSP\n| summarize NUMERO_EVENTI=count() by tipoEvento\n| sort by NUMERO_EVENTI desc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Distribuzione $FAULTCODE nel tempo da PSP: $PSP",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nlet diff_in_seconds=datetime_diff('second', end, start);\nlet _step = case(\ndiff_in_seconds between (0 .. 60), 1s, // con un range di un minuto, step di un secondo\ndiff_in_seconds between (61 .. 3600), 1m, // con un range di un'ora, step di 1 minuto\ndiff_in_seconds between (3601 .. 10800), 15m, // con un range che va da 1h a 3h, step di 15m\ndiff_in_seconds between (10801 .. 21600), 30m, // con un range che va da 3h a 6h, step di 30m\ndiff_in_seconds between (21601 .. 86399), 1h, // con un range che va da 6h a 24h, step di 1h\ndiff_in_seconds > 86399, 1d, // con un range che va dalle 24h, step di 1d\n1d\n);\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"activatePaymentNotice\",\"verifyPaymentNotice\",\"sendPaymentOutcome\", \"sendPaymentOutcomeV2\", \"nodoInviaRT\", \"nodoAttivaRPT\", \"nodoVerificaRPT\", \"verificaBollettino\")\n| where faultCode == $FAULTCODE\n| where psp == $PSP\n| summarize NUMERO_EVENTI=count() by bin(insertedTimestamp, _step)\n| extend insertedTimestamp = datetime_local_to_utc(insertedTimestamp, \"Europe/Rome\")\n| sort by NUMERO_EVENTI desc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Dettaglio $FAULTCODE su $PSP",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"activatePaymentNotice\",\"verifyPaymentNotice\",\"sendPaymentOutcome\", \"sendPaymentOutcomeV2\", \"nodoInviaRT\", \"nodoAttivaRPT\", \"nodoVerificaRPT\", \"verificaBollettino\")\n| where faultCode == $FAULTCODE\n| where psp == $PSP\n| extend insertedTimestamp = datetime_local_to_utc(insertedTimestamp, \"Europe/Rome\")\n| project insertedTimestamp, tipoEvento, idDominio, iuv, ccp, faultCode, faultDescription, sessionId\n",
     "querySource": "raw"
    }
   ]
  }
 ]
}