{
 "title": "[CONFIG] - Migrazioni Enti/Stazioni",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "intermediario",
    "label": "Partner Tecnologico",
    "query": {
     "query": "INTERMEDIARI_PA\n| extend variable = strcat(ID_INTERMEDIARIO_PA,\"|\",INTERMEDIARIO_DESCR)\n| extend v = strcat(ID_INTERMEDIARIO_PA, \" |\", INTERMEDIARIO_DESCR)\n| sort by INTERMEDIARIO_DESCR asc\n| project variable"
    }
   },
   {
    "name": "stazione",
    "label": "Stazione",
    "query": {
     "query": "PT_REL_PA\n| where ID_INTERMEDIARIO == $intermediario\n| extend l = strcat(STAZIONE,\"|\",STAZIONE, \" (v\", VERSIONE, \")\")\n| project l"
    }
   },
   {
    "name": "id_dominio",
    "label": "Ente Creditore",
    "query": {
     "query": "PA\n| where ENABLED == \"Y\"\n| extend DESCR=case(isempty(RAGIONE_SOCIALE), DESCRIZIONE, RAGIONE_SOCIALE)\n| extend l = strcat(ID_DOMINIO,\"|\", \"(\", ID_DOMINIO,\") \", DESCR)\n| project l"
    }
   },
   { "name": "STATE", "query": "Ibrido,Solo V1,Solo V2" }
  ]
 },
 "panels": [
  {
   "title": "Visuale globale su enti/stazioni",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Percentuale delle associazioni ente/stazione",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "PT_REL_PA\n| where STAZIONE_ENABLED == \"Y\"\n| summarize TOTALE=count() by VERSIONE\n| extend label=strcat(\"Stazione v\", VERSIONE)\n| project label, TOTALE",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Numero di stazioni singole presenti sul nodo",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "PT_REL_PA\n| where STAZIONE_ENABLED == \"Y\"\n| project STAZIONE, VERSIONE\n| distinct STAZIONE, VERSIONE\n| summarize TOTALE=count() by VERSIONE\n| extend label=strcat(\"Stazioni a v\", VERSIONE)\n| project label, TOTALE\n",
       "querySource": "raw"
      }
     ]
    }
   ]
  },
  {
   "title": "Dettaglio Intermediario: $intermediario",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distribuzione Enti su Stazioni",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "PT_REL_PA\n| where ID_INTERMEDIARIO == $intermediario\n| extend l = strcat(STAZIONE, \" (v\", VERSIONE, \")\")\n| project-away STAZIONE\n| project-rename STAZIONE=l\n| summarize TOTALE=count() by STAZIONE",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "$intermediario / $stazione",
     "type": "table",
     "gridPos": { "h": 7, "w": 14, "x": 10, "y": 2 },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "PT_REL_PA\n| where ID_INTERMEDIARIO == $intermediario\n| where STAZIONE == $stazione",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Lista intermediati : $intermediario",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "PT_REL_PA\n| where ID_INTERMEDIARIO == $intermediario",
       "querySource": "raw"
      }
     ]
    }
   ]
  },
  {
   "title": "Dettaglio su Ente Creditore: $id_dominio",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Ente Creditore: $id_dominio",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "PT_REL_PA\n| where ID_DOMINIO in ($id_dominio)\n| project-away TIMEOUT, TIMEOUT_A, TIMEOUT_B, TIMEOUT_C, PA_RAGIONE_SOCIALE \n| project-rename INTERMEDIARIO=INTERMEDIARIO_DESCR , PA=PA_DESCR , ENABLED=STAZIONE_ENABLED, VER=VERSIONE, BCAST=BROADCAST, SEGR=SEGREGAZIONE , PROG=PROGRESSIVO \n| sort by INTERMEDIARIO asc\n| project ID_INTERMEDIARIO , INTERMEDIARIO , ID_DOMINIO , PA, STAZIONE, VER , BCAST, ENABLED, AUX_DIGIT , SEGR , PROG\n| join kind=inner PA on $left.ID_DOMINIO == $right.ID_DOMINIO\n| extend PA_DESCR=case(isempty(RAGIONE_SOCIALE), DESCRIZIONE, RAGIONE_SOCIALE)\n| project ID_INTERMEDIARIO , INTERMEDIARIO , ID_DOMINIO , PA_DESCR, STAZIONE, VER , BCAST, ENABLED, AUX_DIGIT , SEGR , PROG\n| project-rename  PA=PA_DESCR",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Stato Migrazione PT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Tipologia stazioni su Intermediari",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let Int_V1 = PT_REL_PA\n| where STAZIONE_ENABLED == \"Y\"\n| distinct ID_INTERMEDIARIO, VERSIONE, STAZIONE\n| where VERSIONE == 1\n| summarize TOTALE_V1=count() by ID_INTERMEDIARIO, VERSIONE;\nlet Int_V2 = PT_REL_PA\n| where STAZIONE_ENABLED == \"Y\"\n| distinct ID_INTERMEDIARIO, VERSIONE, STAZIONE\n| where VERSIONE == 2\n| summarize TOTALE_V2=count() by ID_INTERMEDIARIO, VERSIONE;\nINTERMEDIARI_PA\n| where ENABLED == \"Y\"\n| project-rename ID_INTERMEDIARIO=ID_INTERMEDIARIO_PA\n| join kind=leftouter Int_V1 on ID_INTERMEDIARIO\n| join kind=leftouter Int_V2 on ID_INTERMEDIARIO\n| extend TOTALE_V1=case(isnull(TOTALE_V1),0,TOTALE_V1)\n| extend TOTALE_V2=case(isnull(TOTALE_V2),0,TOTALE_V2)\n| extend TOTALE=TOTALE_V1+TOTALE_V2\n| extend STATE = case(TOTALE_V1==0,\"Solo V2\", TOTALE_V2==0, \"Solo V1\", \"Ibrido\")\n| where TOTALE > 0\n| project ID_INTERMEDIARIO, INTERMEDIARIO_DESCR, STATE, TOTALE_V1, TOTALE_V2, TOTALE\n| summarize Situazione=count() by STATE",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Elenco Intermediati - $STATE",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let Int_V1 = PT_REL_PA\n| where STAZIONE_ENABLED == \"Y\"\n| distinct ID_INTERMEDIARIO, VERSIONE, STAZIONE\n| where VERSIONE == 1\n| summarize TOTALE_V1=count() by ID_INTERMEDIARIO, VERSIONE;\nlet Int_V2 = PT_REL_PA\n| where STAZIONE_ENABLED == \"Y\"\n| distinct ID_INTERMEDIARIO, VERSIONE, STAZIONE\n| summarize TOTALE_V2=count() by ID_INTERMEDIARIO, VERSIONE\n| where VERSIONE == 2;\nINTERMEDIARI_PA\n| where ENABLED == \"Y\"\n| project-rename ID_INTERMEDIARIO=ID_INTERMEDIARIO_PA\n| join kind=leftouter Int_V1 on ID_INTERMEDIARIO\n| join kind=leftouter Int_V2 on ID_INTERMEDIARIO\n| extend TOTALE_V1=case(isnull(TOTALE_V1),0,TOTALE_V1)\n| extend TOTALE_V2=case(isnull(TOTALE_V2),0,TOTALE_V2)\n| extend TOTALE=TOTALE_V1+TOTALE_V2\n| extend STATE = case(TOTALE_V1==0,\"Solo V2\", TOTALE_V2==0, \"Solo V1\", \"Ibrido\")\n| where TOTALE > 0\n| where STATE in ($STATE)\n| project-rename CF=ID_INTERMEDIARIO, INTERMEDIARIO=INTERMEDIARIO_DESCR, V1=TOTALE_V1, V2=TOTALE_V2\n| sort by INTERMEDIARIO asc\n| project CF, INTERMEDIARIO, V1, V2, TOTALE\n",
     "querySource": "raw"
    }
   ]
  }
 ]
}