{
 "title": "Monitor Nodo",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "PA",
    "label": "Ente Creditore",
    "query": {
     "query": "PA\n| where ENABLED == \"Y\"\n| extend l = strcat(ID_DOMINIO,\"|\", \"(\", ID_DOMINIO,\") \", DESCRIZIONE)\n| project l"
    }
   },
   {
    "name": "PSP",
    "label": "PSP",
    "query": {
     "query": "PSP\n| where ENABLED == \"Y\"\n| extend l = strcat(ID_PSP,\"|\", \"(\", ID_PSP,\") \", RAGIONE_SOCIALE)\n| project l"
    }
   },
   {
    "name": "faultCode",
    "label": "Fault Code",
    "query": {
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from + 7200000));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to + 7200000));\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where faultCode startswith \"PPT_\"\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| distinct faultCode"
    }
   },
   { "name": "Step", "label": "Campionamento", "query": "1m, 5m, 10m, 30m, 1h" }
  ]
 },
 "panels": [
  {
   "title": "PPT_SYSTEM_ERROR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distribuzione PPT_SYSTEM_ERROR nel tempo",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from + 7200000));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to + + 7200000));\nlet _step=$Step;\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where faultCode == \"PPT_SYSTEM_ERROR\"\n| make-series count() default=0 on insertedTimestamp in range(todatetime(unixtime_milliseconds_todatetime($__from + 7200000)), todatetime(unixtime_milliseconds_todatetime($__to + 7200000)), _step)\n| mvexpand count_, insertedTimestamp\n| extend insertedTimestamp=datetime_add(\"hour\", -2, todatetime(insertedTimestamp))\n| extend insertedTimestamp=todatetime(insertedTimestamp)\n| extend count_=toint(count_)\n| project insertedTimestamp, count_\n| sort by insertedTimestamp asc\n//| summarize TOTALE=count() by bin(insertedTimestamp, _step)\n//| extend insertedTimestamp=format_datetime(insertedTimestamp, \"HH:mm\")\n//| extend Fascia=insertedTimestamp \n//| project insertedTimestamp , Fascia, TOTALE\n//| sort by insertedTimestamp asc\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Distribuzione PPT_SYSTEM_ERROR su PA",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from + 7200000));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to + + 7200000));\nlet _step=$Step;\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where faultCode == \"PPT_SYSTEM_ERROR\"\n| summarize TOTALE=count() by idDominio\n| join kind=inner PA on $left.idDominio == $right.ID_DOMINIO\n| sort by TOTALE desc\n| project DESCRIZIONE, TOTALE\n\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Distribuzione PPT_SYSTEM_ERROR su PSP",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from + 7200000));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to + + 7200000));\nlet _step=$Step;\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where faultCode == \"PPT_SYSTEM_ERROR\"\n| summarize TOTALE=count() by psp\n| join kind=inner PSP on $left.psp == $right.ID_PSP\n| sort by TOTALE desc\n| project DESCRIZIONE, TOTALE\n\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Distribuzione PPT_SYSTEM_ERROR su PSP",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from + 7200000));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to + + 7200000));\nlet _step=$Step;\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where faultCode == \"PPT_SYSTEM_ERROR\"\n| project insertedTimestamp, tipoEvento, psp, iuv, idDominio, ccp, faultCode, faultDescription\n\n",
       "querySource": "raw"
      }
     ]
    }
   ]
  },
  { "title": "Andamento Generale", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Errori forniti alle PA",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where faultCode startswith \"PPT_\"\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in (\"nodoInviaCarrelloRPT\",\"nodoInviaRPT\")\n| summarize count() by idDominio\n| join kind=inner PA on $left.idDominio == $right.ID_DOMINIO\n| project RAGIONE_SOCIALE, count_\n| sort by count_ desc\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Distribuzione Fault Code vs. PA",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where faultCode startswith \"PPT_\"\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in (\"nodoInviaCarrelloRPT\",\"nodoInviaRPT\")\n| summarize count() by faultCode\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Fault Code forniti al PSP",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where faultCode startswith \"PPT_\"\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in (\"verifyPaymentNotice\",\"activatePaymentNotice\",\"sendPaymentOutcome\", \"sendPaymentOutcomeV2\", \"verificaBollettino\", \"activateIOPayment\", \"nodoVerificaRPT\", \"nodoAttivaRPT\", \"nodoInviaRT\",\"nodoChiediNumeroAvviso\",\"activatePaymentNoticeV2\")\n| summarize count() by psp\n| join kind=inner PSP on $left.psp == $right.ID_PSP\n| project RAGIONE_SOCIALE, count_\n| sort by count_ desc\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Distribuzione Fault Code vs. PSP",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where faultCode startswith \"PPT_\"\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in (\"verifyPaymentNotice\",\"activatePaymentNotice\",\"sendPaymentOutcome\", \"sendPaymentOutcomeV2\", \"verificaBollettino\", \"activateIOPayment\", \"nodoVerificaRPT\", \"nodoAttivaRPT\", \"nodoInviaRT\",\"nodoChiediNumeroAvviso\",\"activatePaymentNoticeV2\")\n| summarize count() by faultCode\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Distribuzione nel tempo",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nlet _step=$Step;\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where faultCode startswith \"PPT_\"\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in (\"nodoInviaCarrelloRPT\",\"nodoInviaRPT\")\n| summarize TOTALE=count() by bin(insertedTimestamp, _step)\n| extend insertedTimestamp=format_datetime(insertedTimestamp, \"HH:mm\")\n| extend Fascia=insertedTimestamp \n| project insertedTimestamp , Fascia, TOTALE\n| sort by insertedTimestamp asc, Fascia\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Vista per PA: $PA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distribuzione Fault Code: $PA",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from + 7200000));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to + 7200000));\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where faultCode startswith \"PPT_\"\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in (\"nodoInviaCarrelloRPT\",\"nodoInviaRPT\")\n| where idDominio == $PA\n//| where faultCode in ($faultCode)\n| summarize count() by faultCode\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Distribuzione Fault Code: $PA / FaultCode: $faultCode",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from + 7200000));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to + 7200000));\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where faultCode startswith \"PPT_\"\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in (\"nodoInviaCarrelloRPT\",\"nodoInviaRPT\")\n| where idDominio == $PA\n| where faultCode in ($faultCode)\n| summarize count() by tipoEvento\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Distribuzione fault nel tempo",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from + 7200000));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to + 7200000));\nlet _step=$Step;\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where faultCode startswith \"PPT_\"\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in (\"nodoInviaCarrelloRPT\",\"nodoInviaRPT\")\n| where idDominio == $PA\n| where faultCode in ($faultCode)\n| summarize TOTALE=count() by bin(insertedTimestamp, _step)\n| extend insertedTimestamp=format_datetime(insertedTimestamp, \"HH:mm\")\n| extend Fascia=insertedTimestamp \n| project insertedTimestamp , Fascia, TOTALE\n| sort by insertedTimestamp asc, Fascia\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Dettaglio eventi",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from + 7200000));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to + 7200000));\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where faultCode startswith \"PPT_\"\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in (\"nodoInviaCarrelloRPT\",\"nodoInviaRPT\")\n| where idDominio == $PA\n| where faultCode in ($faultCode)\n| extend insertedTimestamp=datetime_add(\"hour\", -2, insertedTimestamp)\n| project insertedTimestamp, idDominio, iuv, ccp, tipoEvento, faultCode, faultDescription\n| sort by insertedTimestamp desc",
       "querySource": "raw"
      }
     ]
    }
   ]
  },
  { "title": "Vista per PSP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Distribuzione Fault Code: $PSP",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from + 7200000));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to + 7200000));\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where faultCode startswith \"PPT_\"\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in (\"verifyPaymentNotice\",\"activatePaymentNotice\",\"sendPaymentOutcome\", \"sendPaymentOutcomeV2\", \"verificaBollettino\", \"activateIOPayment\", \"nodoVerificaRPT\", \"nodoAttivaRPT\", \"nodoInviaRT\",\"nodoChiediNumeroAvviso\",\"activatePaymentNoticeV2\")\n| where psp == $PSP\n| summarize count() by faultCode\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Distribuzione Fault Code: $PSP",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from + 7200000));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to + 7200000));\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where faultCode startswith \"PPT_\"\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in (\"verifyPaymentNotice\",\"activatePaymentNotice\",\"sendPaymentOutcome\", \"sendPaymentOutcomeV2\", \"verificaBollettino\", \"activateIOPayment\", \"nodoVerificaRPT\", \"nodoAttivaRPT\", \"nodoInviaRT\",\"nodoChiediNumeroAvviso\",\"activatePaymentNoticeV2\")\n| where psp == $PSP\n| where faultCode in ($faultCode)\n| summarize count() by tipoEvento\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Distribuzione fault nel tempo",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from + 7200000));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to + 7200000));\nlet _step=$Step;\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where faultCode startswith \"PPT_\"\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in (\"verifyPaymentNotice\",\"activatePaymentNotice\",\"sendPaymentOutcome\", \"verificaBollettino\", \"sendPaymentOutcomeV2\", \"activateIOPayment\", \"nodoVerificaRPT\", \"nodoAttivaRPT\", \"nodoInviaRT\",\"nodoChiediNumeroAvviso\",\"activatePaymentNoticeV2\")\n| where psp == $PSP\n| where faultCode in ($faultCode)\n| summarize TOTALE=count() by bin(insertedTimestamp, _step)\n| extend insertedTimestamp=format_datetime(insertedTimestamp, \"HH:mm\")\n| extend Fascia=insertedTimestamp \n| project insertedTimestamp , Fascia, TOTALE\n| sort by insertedTimestamp asc, Fascia\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Dettaglio eventi",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from + 7200000));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to + 7200000));\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where faultCode startswith \"PPT_\"\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in (\"verifyPaymentNotice\",\"activatePaymentNotice\",\"sendPaymentOutcome\", \"sendPaymentOutcomeV2\", \"verificaBollettino\", \"activateIOPayment\", \"nodoVerificaRPT\", \"nodoAttivaRPT\", \"nodoInviaRT\",\"nodoChiediNumeroAvviso\",\"activatePaymentNoticeV2\")\n| where psp == $PSP\n| where faultCode in ($faultCode)\n| extend insertedTimestamp=datetime_add(\"hour\", -2, insertedTimestamp)\n| project insertedTimestamp, idDominio, iuv, ccp, tipoEvento, faultCode, faultDescription, sessionId\n| sort by insertedTimestamp desc",
     "querySource": "raw"
    }
   ]
  }
 ]
}