{
 "title": "[NC] - Monitoraggio LisPAY",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "LISPay - Canale Nuova Connettività",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Totale verifyPaymentNotice",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to));\nReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento == \"verifyPaymentNotice\"\n| where sottoTipoEvento == \"REQ\"\n| where canale == \"08658331007_04\"\n| summarize TOTALE=count()",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Totale activatePaymentNotice",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to));\nReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento == \"verifyPaymentNotice\"\n| where sottoTipoEvento == \"REQ\"\n| where canale == \"08658331007_04\"\n| summarize TOTALE=count()",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Totale sendPaymentOutcome",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to));\nReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento == \"sendPaymentOutcome\"\n| where sottoTipoEvento == \"REQ\"\n| where canale == \"08658331007_04\"\n| summarize TOTALE=count()",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Fault Code Restituiti a LISPay su verifyPaymentNotice",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to));\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where canale == \"08658331007_04\"\n| where tipoEvento == \"verifyPaymentNotice\"\n| summarize TOTALE=count() by faultCode",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Fault Code Restituiti a LISPay su activatePaymentNotice",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to));\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where canale == \"08658331007_04\"\n| where tipoEvento == \"activatePaymentNotice\"\n| summarize TOTALE=count() by faultCode",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Fault Code Restituiti a LISPay su sendPaymentOutcome",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to));\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where canale == \"08658331007_04\"\n| where tipoEvento == \"sendPaymentOutcome\"\n| summarize TOTALE=count() by faultCode",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Tempi verifyPaymentNotice",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to));\nlet verifyPaymentNotice_req = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento == \"verifyPaymentNotice\"\n| where categoriaEvento == \"INTERFACCIA\"\n| where sottoTipoEvento == \"REQ\"\n| where canale == \"08658331007_04\"\n| project dataOraEvento, idDominio, iuv, ccp, psp, sessionId, stazione;\nlet verifyPaymentNotice_Resp = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento == \"verifyPaymentNotice\"\n| where categoriaEvento == \"INTERFACCIA\"\n| where sottoTipoEvento == \"RESP\"\n| where canale == \"08658331007_04\"\n| project dataOraEvento, idDominio, iuv, ccp, psp, sessionId;\nverifyPaymentNotice_req\n| join kind=leftouter verifyPaymentNotice_Resp on idDominio, iuv, ccp, sessionId\n| project-rename REQUEST_TIMESTAMP=dataOraEvento, RESPONSE_TIMESTAMP=dataOraEvento1\n| extend intermediario = substring(stazione, 0, strlen(stazione)-3)\n| extend diff_time=datetime_diff(\"millisecond\", RESPONSE_TIMESTAMP, REQUEST_TIMESTAMP)\n//| project REQUEST_TIMESTAMP, RESPONSE_TIMESTAMP, diff_time, idDominio, iuv, ccp, intermediario\n| project REQUEST_TIMESTAMP, diff_time, intermediario\n| join kind=inner INTERMEDIARI_PA on $left.intermediario == $right.ID_INTERMEDIARIO_PA\n| project REQUEST_TIMESTAMP, INTERMEDIARIO=INTERMEDIARIO_DESCR, diff_time\n| sort by REQUEST_TIMESTAMP asc, INTERMEDIARIO, diff_time\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Tempi activatePaymentNotice",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to));\nlet verifyPaymentNotice_req = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento == \"activatePaymentNotice\"\n| where categoriaEvento == \"INTERFACCIA\"\n| where sottoTipoEvento == \"REQ\"\n| where canale == \"08658331007_04\"\n| project dataOraEvento, idDominio, iuv, ccp, psp, sessionId, stazione;\nlet verifyPaymentNotice_Resp = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento == \"activatePaymentNotice\"\n| where categoriaEvento == \"INTERFACCIA\"\n| where sottoTipoEvento == \"RESP\"\n| where canale == \"08658331007_04\"\n| project dataOraEvento, idDominio, iuv, ccp, psp, sessionId;\nverifyPaymentNotice_req\n| join kind=leftouter verifyPaymentNotice_Resp on idDominio, iuv, ccp, sessionId\n| project-rename REQUEST_TIMESTAMP=dataOraEvento, RESPONSE_TIMESTAMP=dataOraEvento1\n| extend intermediario = substring(stazione, 0, strlen(stazione)-3)\n| extend diff_time=datetime_diff(\"millisecond\", RESPONSE_TIMESTAMP, REQUEST_TIMESTAMP)\n//| project REQUEST_TIMESTAMP, RESPONSE_TIMESTAMP, diff_time, idDominio, iuv, ccp, intermediario\n| project REQUEST_TIMESTAMP, diff_time, intermediario\n| join kind=inner INTERMEDIARI_PA on $left.intermediario == $right.ID_INTERMEDIARIO_PA\n| project REQUEST_TIMESTAMP, INTERMEDIARIO=INTERMEDIARIO_DESCR, diff_time\n| sort by REQUEST_TIMESTAMP asc, INTERMEDIARIO, diff_time\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "LISpay - GAD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Totale verifyPaymentNotice",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to));\nReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento == \"verifyPaymentNotice\"\n| where sottoTipoEvento == \"REQ\"\n| extend canale_int = substring(canale, 0, strlen(canale)-3)\n| where canale_int == \"08658331007\"\n| where canale != \"08658331007_04\"\n| summarize TOTALE=count()",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Totale activatePaymentNotice",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to));\nReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento == \"activatePaymentNotice\"\n| where sottoTipoEvento == \"REQ\"\n| extend canale_int = substring(canale, 0, strlen(canale)-3)\n| where canale_int == \"08658331007\"\n| where canale != \"08658331007_04\"\n| summarize TOTALE=count()",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Totale sendPaymentOutcome",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to));\nReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento == \"sendPaymentOutcome\"\n| where sottoTipoEvento == \"REQ\"\n| extend canale_int = substring(canale, 0, strlen(canale)-3)\n| where canale_int == \"08658331007\"\n| where canale != \"08658331007_04\"\n| summarize TOTALE=count()",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Fault Code Restituiti a LISPay su verifyPaymentNotice",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to));\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento == \"verifyPaymentNotice\"\n| extend canale_int = substring(canale, 0, strlen(canale)-3)\n| where canale_int == \"08658331007\"\n| where canale != \"08658331007_04\"\n| summarize TOTALE=count() by faultCode",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Fault Code Restituiti a LISPay su activatePaymentNotice",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to));\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento == \"activatePaymentNotice\"\n| extend canale_int = substring(canale, 0, strlen(canale)-3)\n| where canale_int == \"08658331007\"\n| where canale != \"08658331007_04\"\n| summarize TOTALE=count() by faultCode",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Fault Code Restituiti a LISPay su sendPaymentOutcome",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to));\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento == \"activatePaymentNotice\"\n| extend canale_int = substring(canale, 0, strlen(canale)-3)\n| where canale_int == \"08658331007\"\n| where canale != \"08658331007_04\"\n| summarize TOTALE=count() by faultCode",
       "querySource": "raw"
      }
     ]
    }
   ]
  }
 ]
}