{
 "title": "Monitoraggio PT",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "IntermediarioPa",
    "label": "Partner Tecnologico",
    "query": "INTERMEDIARI_PA\n| extend variable = strcat(ID_INTERMEDIARIO_PA,\"|\",INTERMEDIARIO_DESCR)\n| extend v = strcat(ID_INTERMEDIARIO_PA, \" : \", INTERMEDIARIO_DESCR)\n| sort by INTERMEDIARIO_DESCR asc\n| project variable"
   },
   {
    "name": "Stazione",
    "label": "Stazione",
    "query": "PT_REL_PA\n| where ID_INTERMEDIARIO == $IntermediarioPa\n| extend v = strcat(STAZIONE, \"|\", STAZIONE)\n| sort by STAZIONE asc\n| project v"
   },
   {
    "name": "EC",
    "label": "EC",
    "query": "PT_REL_PA\n| where ID_INTERMEDIARIO in ($IntermediarioPa)\n| where STAZIONE in ($Stazione)\n| extend v = strcat(ID_DOMINIO, \"|\", PA_DESCR)\n| sort by PA_DESCR asc\n| project v"
   },
   {
    "name": "IntermediarioPSP",
    "label": "PSP Intermediario",
    "query": "INTERMEDIARI_PSP\n| extend variable = strcat(ID_INTERMEDIARIO_PSP,\"|\",INTERMEDIARIO_DESCR)\n| extend v = strcat(ID_INTERMEDIARIO_PSP, \" : \", INTERMEDIARIO_DESCR)\n| sort by INTERMEDIARIO_DESCR asc\n| project variable"
   },
   {
    "name": "PSP",
    "label": "PSP",
    "query": "PT_REL_PSP\n| where ID_INTERMEDIARIO in ($IntermediarioPSP)\n| where CANALE_ENABLED == \"Y\"\n| extend v = strcat(ID_PSP, \"|\", PSP_RAGIONE_SOCIALE)\n| distinct v\n| project v"
   },
   {
    "name": "Step",
    "label": "Campionameno",
    "query": "10s, 30s, 1m, 5m, 15m, 30m, 1h, 2h"
   },
   { "name": "ms_offset", "query": "7200000" },
   { "name": "h_offset", "query": "-2" }
  ]
 },
 "panels": [
  {
   "title": "Fase di Verifica",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Totale verifyPaymentNotice pervenute dai PSP",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"verifyPaymentNotice\", \"nodoVerificaRPT\",\"verificaBollettino\")\n| where categoriaEvento == \"INTERFACCIA\"\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0, strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| summarize TOTALE=count() by sottoTipoEvento, stazione, idDominio, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Totale verifyPaymentNotice risposte ai PSP",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"verifyPaymentNotice\", \"nodoVerificaRPT\",\"verificaBollettino\")\n| where categoriaEvento == \"INTERFACCIA\"\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0, strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| summarize TOTALE=count() by sottoTipoEvento, stazione, idDominio, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Totale Request di Verifica agli EC",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"paVerifyPaymentNotice\", \"paaVerificaRPT\")\n| where categoriaEvento == \"INTERFACCIA\"\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0, strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| summarize TOTALE=count() by sottoTipoEvento, stazione, idDominio, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Totale Response di Verifica ricevute dagli EC",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"paVerifyPaymentNotice\", \"paaVerificaRPT\")\n| where categoriaEvento == \"INTERFACCIA\"\n| where sottoTipoEvento == \"RESP\"\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0, strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| summarize TOTALE=count() by sottoTipoEvento, stazione, idDominio, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Distribuzione Verifiche PSP Intermediari",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nReEvent \n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where tipoEvento in~ ('nodoVerificaRPT', 'verifyPaymentNotice', 'verificaBollettino')\n| where sottoTipoEvento == \"REQ\"\n| summarize TOTALE=count() by idDominio, stazione, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOT=sum(TOTALE) by intermediario_psp\n| join kind=inner INTERMEDIARI_PSP on $left.intermediario_psp == $right.ID_INTERMEDIARIO_PSP\n| extend INTERMEDIARIO_DESCR=case(ID_INTERMEDIARIO_PSP == \"97735020584\",\"TouchPoing PagoPA\",INTERMEDIARIO_DESCR)\n| project INTERMEDIARIO_DESCR, TOT\n\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Distribuzione Verifiche PSP Intermediati",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nReEvent \n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where tipoEvento in~ ('nodoVerificaRPT', 'verifyPaymentNotice', 'verificaBollettino')\n| where sottoTipoEvento == \"REQ\"\n| summarize TOTALE=count() by idDominio, stazione, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOT=sum(TOTALE) by psp\n| join kind=inner PSP on $left.psp == $right.ID_PSP\n| extend RAGIONE_SOCIALE=case(psp == \"AGID_01\",\"TouchPoing PagoPA\",RAGIONE_SOCIALE)\n| project RAGIONE_SOCIALE, TOT\n\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Distribuzione Fault Infrastrutturali",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where faultCode in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in~ ('nodoVerificaRPT', 'verifyPaymentNotice', 'verificaBollettino')\n| summarize TOTALE=count() by idDominio, faultCode, stazione, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOT=sum(TOTALE) by faultCode\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Distribuzione Fault Applicativi",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in~ ('nodoVerificaRPT', 'verifyPaymentNotice', 'verificaBollettino')\n| summarize TOTALE=count() by idDominio, faultCode, stazione, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOT=sum(TOTALE) by faultCode\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "PSP Intermediari Impattati (infr.)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where faultCode in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in~ ('nodoVerificaRPT', 'verifyPaymentNotice', 'verificaBollettino')\n| summarize TOTALE=count() by idDominio, faultCode, stazione, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOT=sum(TOTALE) by intermediario_psp\n| join kind=inner INTERMEDIARI_PSP on $left.intermediario_psp == $right.ID_INTERMEDIARIO_PSP\n| extend INTERMEDIARIO_DESCR = case(intermediario_psp == \"97735020584\", \"TouchPoing PagoPA\", INTERMEDIARIO_DESCR)\n| project INTERMEDIARIO_DESCR, TOT",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "PSP Intermediari Impattati (appl.)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in~ ('nodoVerificaRPT', 'verifyPaymentNotice', 'verificaBollettino')\n| summarize TOTALE=count() by idDominio, faultCode, stazione, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOT=sum(TOTALE) by intermediario_psp\n| join kind=inner INTERMEDIARI_PSP on $left.intermediario_psp == $right.ID_INTERMEDIARIO_PSP\n| extend INTERMEDIARIO_DESCR = case(intermediario_psp == \"97735020584\", \"TouchPoing PagoPA\", INTERMEDIARIO_DESCR)\n| project INTERMEDIARIO_DESCR, TOT \n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "PSP Intermediati Impattati (infr.)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where faultCode in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in~ ('nodoVerificaRPT', 'verifyPaymentNotice', 'verificaBollettino')\n| summarize TOTALE=count() by idDominio, faultCode, stazione, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOT=sum(TOTALE) by psp\n| join kind=inner PSP on $left.psp == $right.ID_PSP\n| extend RAGIONE_SOCIALE = case(psp == \"AGID_01\", \"Touchpoing PagoPA\", RAGIONE_SOCIALE)\n| project RAGIONE_SOCIALE, TOT\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "PSP Intermediati Impattati (appl.)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in~ ('nodoVerificaRPT', 'verifyPaymentNotice', 'verificaBollettino')\n| summarize TOTALE=count() by idDominio, faultCode, stazione, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOT=sum(TOTALE) by psp\n| join kind=inner PSP on $left.psp == $right.ID_PSP\n| extend RAGIONE_SOCIALE = case(psp == \"AGID_01\", \"Touchpoing PagoPA\", RAGIONE_SOCIALE)\n| project RAGIONE_SOCIALE, TOT\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "EC Intermediati Impattati (infr.)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where faultCode in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in~ ('nodoVerificaRPT', 'verifyPaymentNotice', 'verificaBollettino')\n| summarize TOTALE=count() by idDominio, faultCode, stazione, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOT=sum(TOTALE) by idDominio\n| join kind=inner PA on $left.idDominio == $right.ID_DOMINIO\n| project RAGIONE_SOCIALE, TOT\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "EC Intermediati Impattati (appl.)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in~ ('nodoVerificaRPT', 'verifyPaymentNotice', 'verificaBollettino')\n| summarize TOTALE=count() by idDominio, faultCode, stazione, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOT=sum(TOTALE) by idDominio\n| join kind=inner PA on $left.idDominio == $right.ID_DOMINIO\n| project RAGIONE_SOCIALE, TOT\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Distribuzione nel tempo Infrastrutturali",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where faultCode in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in~ ('nodoVerificaRPT', 'verifyPaymentNotice')\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOTALE=count() by bin(insertedTimestamp, $Step), faultCode\n| extend insertedTimestamp = datetime_local_to_utc(insertedTimestamp, \"Europe/Rome\")\n| sort by insertedTimestamp asc, faultCode\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Distribuzione nel tempo Applicativi",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in~ ('nodoVerificaRPT', 'verifyPaymentNotice')\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOTALE=count() by bin(insertedTimestamp, $Step), faultCode\n| extend insertedTimestamp = datetime_local_to_utc(insertedTimestamp, \"Europe/Rome\")\n| sort by insertedTimestamp asc, faultCode\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Verifica diretto verso la PA",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nlet verificaReq = ReEvent\n| where insertedTimestamp between (start .. end) \n| where tipoEvento in (\"paaVerificaRPT\", \"paVerifyPaymentNotice\")\n| where sottoTipoEvento == \"REQ\"\n| extend intermediario_pa = substring(stazione, 0 ,strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 ,strlen(canale)-3)\n| where intermediario_pa ==  $IntermediarioPa\n| where idDominio in ($EC)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP);\nlet verificaResp = ReEvent\n| where insertedTimestamp between (start .. end) \n| where tipoEvento in (\"paaVerificaRPT\", \"paVerifyPaymentNotice\")\n| where sottoTipoEvento == \"RESP\"\n| extend intermediario_pa = substring(stazione, 0 ,strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 ,strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where idDominio in ($EC)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP);\nlet verificaReq_Resp = verificaReq\n| join kind=leftouter verificaResp on tipoEvento, idDominio, iuv, sessionId\n| extend diff_ec = datetime_diff(\"millisecond\", insertedTimestamp1, insertedTimestamp)\n| extend diff_ec = case(isnull(diff_ec), 7000, diff_ec)\n| project insertedTimestamp, tipoEvento, idDominio, iuv, ccp, psp, canale, sessionId, diff_ec, insertedTimestamp1;\nverificaReq_Resp\n| extend insertedTimestamp = datetime_local_to_utc(insertedTimestamp, \"Europe/Rome\")\n| join kind=inner PA on $left.idDominio == $right.ID_DOMINIO\n| sort by insertedTimestamp asc\n| project insertedTimestamp , RAGIONE_SOCIALE, diff_ec ",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Range di tempi su Verifica",
     "type": "piechart",
     "gridPos": { "h": 17, "w": 7, "x": 17, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nlet verificaReq = ReEvent\n| where insertedTimestamp between (start .. end) \n| where tipoEvento in (\"paaVerificaRPT\", \"paVerifyPaymentNotice\")\n| where sottoTipoEvento == \"REQ\"\n| extend intermediario_pa = substring(stazione, 0 ,strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 ,strlen(canale)-3)\n| where intermediario_pa ==  $IntermediarioPa\n| where idDominio in ($EC)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP);\nlet verificaResp = ReEvent\n| where insertedTimestamp between (start .. end) \n| where tipoEvento in (\"paaVerificaRPT\", \"paVerifyPaymentNotice\")\n| where sottoTipoEvento == \"RESP\"\n| extend intermediario_pa = substring(stazione, 0 ,strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 ,strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where idDominio in ($EC)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP);\nlet verificaReq_Resp = verificaReq\n| join kind=leftouter verificaResp on tipoEvento, idDominio, iuv, sessionId\n| extend diff_ec = datetime_diff(\"millisecond\", insertedTimestamp1, insertedTimestamp)\n| extend diff_ec = case(isnull(diff_ec), 7000, diff_ec)\n| project insertedTimestamp, tipoEvento, idDominio, iuv, ccp, psp, canale, sessionId, diff_ec, insertedTimestamp1;\nverificaReq_Resp\n| summarize TOTALE=count() by bin(diff_ec, 1000)\n| extend bucket = case(\ndiff_ec == 0, \"< 1 sec\",\ndiff_ec == 1000, \"Tra 1s e 2s\",\ndiff_ec == 2000, \"Tra 2s e 3s\",\ndiff_ec == 3000, \"Tra 3s e 4s\",\ndiff_ec == 4000, \"Tra 4s e 5s\",\ndiff_ec == 5000, \"Tra 5s e 6s\",\ndiff_ec == 6000, \"Tra 6s e 7s\",\ndiff_ec >= 7000, \"TIMEOUT\",\ntostring(diff_ec)\n) \n| summarize TOTALE=sum(TOTALE) by bucket\n| project bucket, TOTALE\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Tempi di verifica visti dal PSP",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 17, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nlet verificaReq = ReEvent\n| where insertedTimestamp between (start .. end) \n| where tipoEvento in (\"nodoVerificaRPT\", \"verifyPaymentNotice\")\n| where sottoTipoEvento == \"REQ\"\n| extend intermediario_pa = substring(stazione, 0 ,strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 ,strlen(canale)-3)\n| where intermediario_pa ==  $IntermediarioPa\n| where idDominio in ($EC)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP);\nlet verificaResp = ReEvent\n| where insertedTimestamp between (start .. end) \n| where tipoEvento in (\"nodoVerificaRPT\", \"verifyPaymentNotice\")\n| where sottoTipoEvento == \"RESP\"\n| extend intermediario_pa = substring(stazione, 0 ,strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 ,strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where idDominio in ($EC)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP);\nlet verificaReq_Resp = verificaReq\n| join kind=leftouter verificaResp on tipoEvento, idDominio, iuv, sessionId\n| extend diff_ec = datetime_diff(\"millisecond\", insertedTimestamp1, insertedTimestamp)\n| extend diff_ec = case(isnull(diff_ec), 7000, diff_ec)\n| project insertedTimestamp, tipoEvento, idDominio, iuv, ccp, psp, canale, sessionId, diff_ec, insertedTimestamp1;\nverificaReq_Resp\n| extend insertedTimestamp = datetime_local_to_utc(insertedTimestamp, \"Europe/Rome\")\n| join kind=inner PA on $left.idDominio == $right.ID_DOMINIO\n| sort by insertedTimestamp asc\n| project insertedTimestamp , RAGIONE_SOCIALE, diff_ec",
       "querySource": "raw"
      }
     ]
    }
   ]
  },
  { "title": "Fase di Attivazione", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Totale activatePaymentNotice pervenute dai PSP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"activateIOPayment\", \"activatePaymentNotice\", \"nodoAttivaRPT\")\n| where categoriaEvento == \"INTERFACCIA\"\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0, strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| summarize TOTALE=count() by sottoTipoEvento, stazione, idDominio, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Totale activatePaymentNotice risposte ai PSP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"activateIOPayment\", \"activatePaymentNotice\", \"nodoAttivaRPT\")\n| where categoriaEvento == \"INTERFACCIA\"\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0, strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| summarize TOTALE=count() by sottoTipoEvento, stazione, idDominio, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Totale Request di Attivazione agli EC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"paGetPayment\", \"paaAttivaRPT\", \"paGetPaymentV2\")\n| where categoriaEvento == \"INTERFACCIA\"\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0, strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| summarize TOTALE=count() by sottoTipoEvento, stazione, idDominio, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Totale Response di Attivazione dagli EC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"paGetPayment\", \"paaAttivaRPT\", \"paGetPaymentV2\")\n| where categoriaEvento == \"INTERFACCIA\"\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0, strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| summarize TOTALE=count() by sottoTipoEvento, stazione, idDominio, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Distribuzione Attivazione PSP Intermediari",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nReEvent \n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where tipoEvento in (\"activateIOPayment\", \"activatePaymentNotice\", \"nodoAttivaRPT\")\n| where sottoTipoEvento == \"REQ\"\n| summarize TOTALE=count() by idDominio, stazione, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOT=sum(TOTALE) by intermediario_psp\n| join kind=inner INTERMEDIARI_PSP on $left.intermediario_psp == $right.ID_INTERMEDIARIO_PSP\n| extend INTERMEDIARIO_DESCR=case(ID_INTERMEDIARIO_PSP == \"97735020584\",\"TouchPoing PagoPA\",INTERMEDIARIO_DESCR)\n| project INTERMEDIARIO_DESCR, TOT\n\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Distribuzione Attivazione PSP Intermediati",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nReEvent \n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where tipoEvento in (\"activateIOPayment\", \"activatePaymentNotice\", \"nodoAttivaRPT\")\n| where sottoTipoEvento == \"REQ\"\n| summarize TOTALE=count() by idDominio, stazione, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOT=sum(TOTALE) by psp\n| join kind=inner PSP on $left.psp == $right.ID_PSP\n| extend RAGIONE_SOCIALE=case(psp == \"AGID_01\",\"TouchPoing PagoPA\",RAGIONE_SOCIALE)\n| project RAGIONE_SOCIALE, TOT\n\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Distribuzione Fault Infrastrutturali",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where faultCode in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in (\"activateIOPayment\", \"activatePaymentNotice\", \"nodoAttivaRPT\")\n| summarize TOTALE=count() by idDominio, faultCode, stazione, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOT=sum(TOTALE) by faultCode\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Distribuzione Fault Applicativi",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in (\"activateIOPayment\", \"activatePaymentNotice\", \"nodoAttivaRPT\")\n| summarize TOTALE=count() by idDominio, faultCode, stazione, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOT=sum(TOTALE) by faultCode\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "PSP Intermediari Impattati (infr.)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where faultCode in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in (\"activateIOPayment\", \"activatePaymentNotice\", \"nodoAttivaRPT\")\n| summarize TOTALE=count() by idDominio, faultCode, stazione, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOT=sum(TOTALE) by intermediario_psp\n| join kind=inner INTERMEDIARI_PSP on $left.intermediario_psp == $right.ID_INTERMEDIARIO_PSP\n| extend INTERMEDIARIO_DESCR = case(intermediario_psp == \"97735020584\", \"TouchPoing PagoPA\", INTERMEDIARIO_DESCR)\n| project INTERMEDIARIO_DESCR, TOT",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "PSP Intermediari Impattati (appl.)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in (\"activateIOPayment\", \"activatePaymentNotice\", \"nodoAttivaRPT\")\n| summarize TOTALE=count() by idDominio, faultCode, stazione, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOT=sum(TOTALE) by intermediario_psp\n| join kind=inner INTERMEDIARI_PSP on $left.intermediario_psp == $right.ID_INTERMEDIARIO_PSP\n| extend INTERMEDIARIO_DESCR = case(intermediario_psp == \"97735020584\", \"TouchPoing PagoPA\", INTERMEDIARIO_DESCR)\n| project INTERMEDIARIO_DESCR, TOT",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "PSP Intermediati Impattati (infr.)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where faultCode in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in (\"activateIOPayment\", \"activatePaymentNotice\", \"nodoAttivaRPT\")\n| summarize TOTALE=count() by idDominio, faultCode, stazione, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOT=sum(TOTALE) by psp\n| join kind=inner PSP on $left.psp == $right.ID_PSP\n| extend RAGIONE_SOCIALE = case(psp == \"AGID_01\", \"Touchpoing PagoPA\", RAGIONE_SOCIALE)\n| project RAGIONE_SOCIALE, TOT\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "PSP Intermediati Impattati (appl.)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in (\"activateIOPayment\", \"activatePaymentNotice\", \"nodoAttivaRPT\")\n| summarize TOTALE=count() by idDominio, faultCode, stazione, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOT=sum(TOTALE) by psp\n| join kind=inner PSP on $left.psp == $right.ID_PSP\n| extend RAGIONE_SOCIALE = case(psp == \"AGID_01\", \"Touchpoing PagoPA\", RAGIONE_SOCIALE)\n| project RAGIONE_SOCIALE, TOT\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "EC Intermediati Impattati (infr.)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where faultCode in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in (\"activateIOPayment\", \"activatePaymentNotice\", \"nodoAttivaRPT\")\n| summarize TOTALE=count() by idDominio, faultCode, stazione, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOT=sum(TOTALE) by idDominio\n| join kind=inner PA on $left.idDominio == $right.ID_DOMINIO\n| project RAGIONE_SOCIALE, TOT\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "EC Intermediati Impattati (appl.)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in (\"activateIOPayment\", \"activatePaymentNotice\", \"nodoAttivaRPT\")\n| summarize TOTALE=count() by idDominio, faultCode, stazione, intermediario_psp, psp\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOT=sum(TOTALE) by idDominio\n| join kind=inner PA on $left.idDominio == $right.ID_DOMINIO\n| project RAGIONE_SOCIALE, TOT\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Distribuzione nel tempo Infrastrutturali",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where faultCode in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in (\"activateIOPayment\", \"activatePaymentNotice\", \"nodoAttivaRPT\")\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOTALE=count() by bin(insertedTimestamp, $Step), faultCode\n| extend insertedTimestamp = datetime_local_to_utc(insertedTimestamp, \"Europe/Rome\")\n| sort by insertedTimestamp asc, faultCode\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Distribuzione nel tempo Applicativi",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| extend intermediario_pa = substring(stazione, 0, strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 , strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where tipoEvento in (\"activateIOPayment\", \"activatePaymentNotice\", \"nodoAttivaRPT\")\n| where stazione in ($Stazione)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP)\n| where idDominio in ($EC)\n| summarize TOTALE=count() by bin(insertedTimestamp, $Step), faultCode\n| extend insertedTimestamp = datetime_local_to_utc(insertedTimestamp, \"Europe/Rome\")\n| sort by insertedTimestamp asc, faultCode\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Attivazioni diretto verso la PA",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nlet activateReq = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"paGetPayment\", \"paaAttivaRPT\")\n| where sottoTipoEvento == \"REQ\"\n| extend intermediario_pa = substring(stazione, 0 ,strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 ,strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where idDominio in ($EC)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP);\nlet activateResp = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"paGetPayment\", \"paaAttivaRPT\")\n| where sottoTipoEvento == \"RESP\"\n| extend intermediario_pa = substring(stazione, 0 ,strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 ,strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where idDominio in ($EC)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP);\nlet activateReq_Resp = activateReq\n| join kind=leftouter activateResp on tipoEvento, idDominio, iuv, sessionId\n| extend diff_act = datetime_diff(\"millisecond\", insertedTimestamp1, insertedTimestamp)\n| extend diff_act = case(isnull(diff_act), 8000, diff_act)\n| project insertedTimestamp, tipoEvento, idDominio, iuv, ccp, psp, canale, sessionId, diff_act, intermediario_pa, intermediario_psp;\nactivateReq_Resp\n| extend insertedTimestamp = datetime_local_to_utc(insertedTimestamp, \"Europe/Rome\")\n| join kind=inner PA on $left.idDominio == $right.ID_DOMINIO\n| sort by insertedTimestamp asc\n| project insertedTimestamp , RAGIONE_SOCIALE, diff_act",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Range di tempi su Attivazione",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 7, "x": 17, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nlet activateReq = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"paGetPayment\", \"paaAttivaRPT\")\n| where sottoTipoEvento == \"REQ\"\n| extend intermediario_pa = substring(stazione, 0 ,strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 ,strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where idDominio in ($EC)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP);\nlet activateResp = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"paGetPayment\", \"paaAttivaRPT\")\n| where sottoTipoEvento == \"RESP\"\n| extend intermediario_pa = substring(stazione, 0 ,strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 ,strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where idDominio in ($EC)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP);\nlet activateReq_Resp = activateReq\n| join kind=leftouter activateResp on tipoEvento, idDominio, iuv, sessionId\n| extend diff_act = datetime_diff(\"millisecond\", insertedTimestamp1, insertedTimestamp)\n| extend diff_act = case(isnull(diff_act), 8000, diff_act)\n| project insertedTimestamp, tipoEvento, idDominio, iuv, ccp, psp, canale, sessionId, diff_act, intermediario_pa, intermediario_psp;\nactivateReq_Resp\n| summarize TOTALE=count() by bin(diff_act, 1000)\n| extend bucket = case(\ndiff_act == 0, \"< 1 sec\",\ndiff_act == 1000, \"Tra 1s e 2s\",\ndiff_act == 2000, \"Tra 2s e 3s\",\ndiff_act == 3000, \"Tra 3s e 4s\",\ndiff_act == 4000, \"Tra 4s e 5s\",\ndiff_act == 5000, \"Tra 5s e 6s\",\ndiff_act == 6000, \"Tra 6s e 7s\",\ndiff_act >= 7000, \"TIMEOUT\",\ntostring(diff_act)\n) \n| summarize TOTALE=sum(TOTALE) by bucket\n| project bucket, TOTALE\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Tempi di Attivazione visti dal PSP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nlet activateReq = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"activateIOPayment\", \"activatePaymentNotice\", \"nodoAttivaRPT\")\n| where sottoTipoEvento == \"REQ\"\n| extend intermediario_pa = substring(stazione, 0 ,strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 ,strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where idDominio in ($EC)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP);\nlet activateResp = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"activateIOPayment\", \"activatePaymentNotice\", \"nodoAttivaRPT\")\n| where sottoTipoEvento == \"RESP\"\n| extend intermediario_pa = substring(stazione, 0 ,strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 ,strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where idDominio in ($EC)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP);\nlet activateReq_Resp = activateReq\n| join kind=leftouter activateResp on tipoEvento, idDominio, iuv, sessionId\n| extend diff_act = datetime_diff(\"millisecond\", insertedTimestamp1, insertedTimestamp)\n| extend diff_act = case(isnull(diff_act), 8000, diff_act)\n| project insertedTimestamp, tipoEvento, idDominio, iuv, ccp, psp, canale, sessionId, diff_act, intermediario_pa, intermediario_psp;\nactivateReq_Resp\n| extend insertedTimestamp = datetime_local_to_utc(insertedTimestamp, \"Europe/Rome\")\n| join kind=inner PA on $left.idDominio == $right.ID_DOMINIO\n| sort by insertedTimestamp asc\n| project insertedTimestamp , RAGIONE_SOCIALE, diff_act",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Fase di Pagamento",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "Invio RT/Receipt verso la PA",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 17, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nlet activateReq = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"paSendRT\", \"paaInviaRT\")\n| where sottoTipoEvento == \"REQ\"\n| extend stazione = case(\ntipoEvento == \"paaInviaRT\",\nextract(\"<identificativoStazioneIntermediarioPA>(.*)</identificativoStazioneIntermediarioPA>\", 1, base64_decode_tostring(payload)),\ntipoEvento == \"paSendRT\",\nextract(\"<idStation>(.*)</idStation>\", 1, base64_decode_tostring(payload)),\nstazione\n ) \n| extend intermediario_pa = substring(stazione, 0 ,strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 ,strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where idDominio in ($EC)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP);\nlet activateResp = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"paSendRT\", \"paaInviaRT\")\n| where sottoTipoEvento == \"RESP\"\n| extend stazione = case(isempty(stazione), \"no\", stazione)\n| extend intermediario_pa = substring(stazione, 0 ,strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 ,strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where idDominio in ($EC)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP);\nlet activateReq_Resp = activateReq\n| join kind=leftouter activateResp on tipoEvento, idDominio, iuv, sessionId\n| extend diff_act = datetime_diff(\"millisecond\", insertedTimestamp1, insertedTimestamp)\n| extend diff_act = case(isnull(diff_act), 8000, diff_act)\n| project insertedTimestamp, tipoEvento, idDominio, iuv, ccp, psp, canale, sessionId, diff_act, intermediario_pa, intermediario_psp;\nactivateReq_Resp\n| extend insertedTimestamp = datetime_local_to_utc(insertedTimestamp, \"Europe/Rome\")\n| join kind=inner PA on $left.idDominio == $right.ID_DOMINIO\n| sort by insertedTimestamp asc\n| project insertedTimestamp , RAGIONE_SOCIALE, diff_act",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Range di tempi su Invio RT/Ricevute",
     "type": "piechart",
     "gridPos": { "h": 17, "w": 7, "x": 17, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nlet activateReq = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"paSendRT\", \"paaInviaRT\")\n| where sottoTipoEvento == \"REQ\"\n| extend intermediario_pa = substring(stazione, 0 ,strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 ,strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where idDominio in ($EC)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP);\nlet activateResp = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in (\"paSendRT\", \"paaInviaRT\")\n| where sottoTipoEvento == \"RESP\"\n| extend intermediario_pa = substring(stazione, 0 ,strlen(stazione)-3)\n| extend intermediario_psp = substring(canale, 0 ,strlen(canale)-3)\n| where intermediario_pa == $IntermediarioPa\n| where idDominio in ($EC)\n| where intermediario_psp in ($IntermediarioPSP)\n| where psp in ($PSP);\nlet activateReq_Resp = activateReq\n| join kind=leftouter activateResp on tipoEvento, idDominio, iuv, sessionId\n| extend diff_act = datetime_diff(\"millisecond\", insertedTimestamp1, insertedTimestamp)\n| extend diff_act = case(isnull(diff_act), 8000, diff_act)\n| project insertedTimestamp, tipoEvento, idDominio, iuv, ccp, psp, canale, sessionId, diff_act, intermediario_pa, intermediario_psp;\nactivateReq_Resp\n| summarize TOTALE=count() by bin(diff_act, 1000)\n| extend bucket = case(\ndiff_act == 0, \"< 1 sec\",\ndiff_act == 1000, \"Tra 1s e 2s\",\ndiff_act == 2000, \"Tra 2s e 3s\",\ndiff_act == 3000, \"Tra 3s e 4s\",\ndiff_act == 4000, \"Tra 4s e 5s\",\ndiff_act == 5000, \"Tra 5s e 6s\",\ndiff_act == 6000, \"Tra 6s e 7s\",\ndiff_act >= 7000, \"TIMEOUT\",\ntostring(diff_act)\n) \n| summarize TOTALE=sum(TOTALE) by bucket\n| project bucket, TOTALE\n",
       "querySource": "raw"
      }
     ]
    }
   ]
  }
 ]
}