{
 "title": "[MONTHLY] - Monitoraggio PT/EC",
 "time": { "from": "now-1M/M", "to": "now-1M/M" },
 "templating": {
  "list": [
   {
    "name": "Step",
    "label": "Campionamento",
    "query": "1m, 10m, 15m, 30m , 1h, 2h, 4h, 6h, 12h, 1d, 2d"
   },
   {
    "name": "IntermediarioPa",
    "label": "Partner Tecnologico",
    "query": "INTERMEDIARI_PA\n| extend variable = strcat(ID_INTERMEDIARIO_PA,\"|\",INTERMEDIARIO_DESCR)\n| extend v = strcat(ID_INTERMEDIARIO_PA, \" : \", INTERMEDIARIO_DESCR)\n| sort by INTERMEDIARIO_DESCR asc\n| project variable"
   },
   {
    "name": "Stazione",
    "label": "Stazione",
    "query": "PT_REL_PA\n| where ID_INTERMEDIARIO == $IntermediarioPa\n| extend v = strcat(STAZIONE, \"|\", STAZIONE)\n| sort by STAZIONE asc\n| project v"
   },
   {
    "name": "EC",
    "label": "Ente Creditore",
    "query": {
     "query": "PT_REL_PA\n| where ID_INTERMEDIARIO in ($IntermediarioPa)\n| where STAZIONE in ($Stazione)\n| extend PA_DESCR=case(isempty(PA_DESCR), PA_RAGIONE_SOCIALE, PA_DESCR)\n| extend v = strcat(ID_DOMINIO,\"|\", \"(\", ID_DOMINIO,\") \", PA_DESCR)\n| sort by PA_DESCR asc\n| project v"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Eventi di Fault",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from + 7200000));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to + 7200000));\nSTAT_MONTH_FAULT_CODE\n| where insertedTimestamp between (start .. end)\n//| extend insertedTimestamp = datetime_add(\\\"hour\\\", -1 , insertedTimestamp)\n| where intermediario == $IntermediarioPa\n| where stazione in ($Stazione)\n| where idDominio in ($EC)\n//| where faultCode in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where faultCode in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO') or faultCode startswith \"PAA\"\n| summarize TOTALE=sum(Eventi)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Eventi di Fault Infrastrutturali",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from + 7200000));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to + 7200000));\nSTAT_MONTH_FAULT_CODE\n| where insertedTimestamp between (start .. end)\n//| extend insertedTimestamp = datetime_add(\"hour\", -1 , insertedTimestamp)\n| where intermediario == $IntermediarioPa\n| where stazione in ($Stazione)\n| where idDominio in ($EC)\n| where faultCode in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| summarize TOTALE=sum(Eventi)\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Eventi di Fault Applicativi",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from + 7200000));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to + 7200000));\nSTAT_MONTH_FAULT_CODE\n| where insertedTimestamp between (start .. end)\n//| extend insertedTimestamp = datetime_add(\"hour\", -1 , insertedTimestamp)\n| where intermediario == $IntermediarioPa\n| where stazione in ($Stazione)\n| where idDominio in ($EC)\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where faultCode startswith \"PAA\"\n| summarize TOTALE=sum(Eventi)\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Distribuzione nel tempo Infrastrutturali",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     },
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nSTAT_MONTH_FAULT_CODE\n| where insertedTimestamp between (start .. end)\n//| extend insertedTimestamp = datetime_add(\"hour\", -1 , insertedTimestamp)\n| where intermediario == $IntermediarioPa\n| where stazione in ($Stazione)\n| where idDominio in ($EC)\n| where faultCode in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n//| where faultCode == \"PAA_SYSTEM_ERROR\"\n| summarize TOTALE=sum(Eventi) by bin(insertedTimestamp, $Step), faultCode\n| extend insertedTimestamp = datetime_local_to_utc(insertedTimestamp, \"Europe/Rome\")\n//| extend insertedTimestamp = format_datetime(insertedTimestamp, \"yyyy-MM-dd\")\n//| extend timestamp = (insertedTimestamp - datetime(1970-01-01)) / 1s \n| sort by insertedTimestamp asc, faultCode",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Distribuzione su Enti",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from + 7200000));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to + 7200000));\nSTAT_MONTH_FAULT_CODE\n| where insertedTimestamp between (start .. end)\n//| extend insertedTimestamp = datetime_add(\"hour\", -2 , insertedTimestamp)\n| where intermediario == $IntermediarioPa\n| where stazione in ($Stazione)\n| where idDominio in ($EC)\n| where faultCode in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n//| where faultCode == \"PAA_SYSTEM_ERROR\"\n| summarize TOTALE=sum(Eventi) by idDominio\n| join kind=inner PA on $left.idDominio == $right.ID_DOMINIO\n| project DESCRIZIONE, TOTALE\n//| extend insertedTimestamp = datetime_add(\"hour\", -2 , insertedTimestamp)\n//| extend insertedTimestamp = format_datetime(insertedTimestamp, \"yyyy-MM-dd\")\n//| extend timestamp = (insertedTimestamp - datetime(1970-01-01)) / 1s \n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Distribuzione nel tempo Applicativi",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     },
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nSTAT_MONTH_FAULT_CODE\n| where insertedTimestamp between (start .. end)\n//| extend insertedTimestamp = datetime_add(\"hour\", -1 , insertedTimestamp)\n| where intermediario == $IntermediarioPa\n| where stazione in ($Stazione)\n| where idDominio in ($EC)\n//| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where faultCode startswith \"PAA_\"\n//| where faultCode == \"PAA_SYSTEM_ERROR\"\n| summarize TOTALE=sum(Eventi) by bin(insertedTimestamp, $Step), faultCode\n| extend insertedTimestamp = datetime_local_to_utc(insertedTimestamp, \"Europe/Rome\")\n//| extend insertedTimestamp = format_datetime(insertedTimestamp, \"yyyy-MM-dd\")\n| sort by insertedTimestamp asc, faultCode",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Distribuzione su Enti",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from + 7200000));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to + 7200000));\nSTAT_MONTH_FAULT_CODE\n| where insertedTimestamp between (start .. end)\n//| extend insertedTimestamp = datetime_add(\"hour\", -1 , insertedTimestamp)\n| where intermediario == $IntermediarioPa\n| where stazione in ($Stazione)\n| where idDominio in ($EC)\n//| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where faultCode startswith \"PAA_\"\n//| where faultCode == \"PAA_SYSTEM_ERROR\"\n| summarize TOTALE=sum(Eventi) by idDominio\n| join kind=inner PA on $left.idDominio == $right.ID_DOMINIO\n| project DESCRIZIONE, TOTALE\n\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Tempi medi di risposta con campionamento a $Step",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 }
  }
 ]
}