{
 "title": "Monitor EC Applicativo",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sdc",
    "query": {
     "query": "INTERMEDIARI_PA\n| extend variable = strcat(ID_INTERMEDIARIO_PA,\"|\",INTERMEDIARIO_DESCR)\n| extend v = strcat(ID_INTERMEDIARIO_PA, \" : \", INTERMEDIARIO_DESCR)\n| sort by INTERMEDIARIO_DESCR asc\n| project variable"
    }
   },
   { "name": "Step", "query": "1m, 10m, 15m, 30m, 1h" },
   {
    "name": "fault",
    "label": "faultCode",
    "query": {
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in~ (\"paaChiediNumeroAvviso\" , \"paaVerificaRPT\" , \"paaAttivaRPT\" , \"paaInviaRT\" , \"paVerifyPaymentNotice\" , \"paGetPayment\" , \"paSendRT\")\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| extend intermediario = tostring(substring(stazione, 0, strlen(stazione)-3))\n| where intermediario == \"$sdc\"\n| summarize sum=count() by faultCode"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "PPT_SINTASSI_XSD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "PPT_SINTASSI_XSD",
     "type": "table",
     "description": "Questi errori sono privi di iuv/idDominio pertanto non possono essere raggruppabili",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where faultCode == 'PPT_SINTASSI_XSD'\n| extend intermediario = substring(stazione, 0, strlen(stazione)-3) \n| project insertedTimestamp, tipoEvento , faultCode , faultDescription, sessionId , sessionIdOriginal , uniqueId \n| extend insertedTimestamp = datetime_add(\"hour\", -1 , insertedTimestamp)\n",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "PPT_SINTASSI_XSD",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 12, "x": 11, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "re",
       "expression": {
        "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where faultCode == 'PPT_SINTASSI_XSD'\n| extend intermediario = substring(stazione, 0, strlen(stazione)-3) \n| summarize cnt=count() by tipoEvento\n",
       "querySource": "raw"
      }
     ]
    }
   ]
  },
  { "title": "Vista Applicativa", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Disservizi Applicativi",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 2 },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in~ (\"paaChiediNumeroAvviso\" , \"paDemandPaymentNotice\", \"paaVerificaRPT\" , \"paaAttivaRPT\" , \"paaInviaRT\" , \"paVerifyPaymentNotice\" , \"paGetPayment\" , \"paSendRT\", \"paGetPaymentV2\", \"paSendRTV2\")\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| extend intermediario = substring(stazione, 0, strlen(stazione)-3) \n| summarize Totale=count() by intermediario\n| where intermediario != \"\"\n| sort by Totale desc \n| top 10 by Totale\n",
     "querySource": "raw"
    },
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "INTERMEDIARI_PA\n| project-rename intermediario=ID_INTERMEDIARIO_PA",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Dettaglio su: $sdc",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nlet okResp = ReEvent\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in~ (\"paaChiediNumeroAvviso\" , \"paDemandPaymentNotice\", \"paaVerificaRPT\" , \"paaAttivaRPT\" , \"paaInviaRT\" , \"paVerifyPaymentNotice\" , \"paGetPayment\" , \"paSendRT\", \"paGetPaymentV2\", \"paSendRTV2\")\n| where sottoTipoEvento == \"RESP\"\n| extend intermediario = tostring(substring(stazione, 0, strlen(stazione)-3))\n| where intermediario == \"$sdc\"\n| extend faultCode = extract(\"<faultCode>(.*)</faultCode>\", 1, base64_decode_tostring(payload))\n| where isempty(faultCode) == true\n| extend faultCode = \"RISPOSTE OK\"\n| summarize sum=count() by faultCode;\nlet koResp = FAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in~ (\"paaChiediNumeroAvviso\" , \"paaVerificaRPT\" , \"paaAttivaRPT\" , \"paaInviaRT\" , \"paVerifyPaymentNotice\" , \"paGetPayment\" , \"paSendRT\", \"paGetPaymentV2\", \"paSendRTV2\")\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| extend intermediario = tostring(substring(stazione, 0, strlen(stazione)-3))\n| where intermediario == \"$sdc\"\n| summarize sum=count() by faultCode;\nunion okResp, koResp",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Distribuzione nel tempo (Campionamento su $Step)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nlet _step=$Step;\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in~ (\"paaChiediNumeroAvviso\" , \"paDemandPaymentNotice\", \"paaVerificaRPT\" , \"paaAttivaRPT\" , \"paaInviaRT\" , \"paVerifyPaymentNotice\" , \"paGetPayment\" , \"paSendRT\", \"paGetPaymentV2\", \"paSendRTV2\")\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where faultCode in ($fault)\n| extend intermediario = tostring(substring(stazione, 0, strlen(stazione)-3))\n| where intermediario == \"$sdc\"\n| summarize TOTALE=count() by bin(insertedTimestamp, $Step)\n| sort by insertedTimestamp asc\n| extend insertedTimestamp=format_datetime(insertedTimestamp, \"HH:mm\")\n| extend Fascia=insertedTimestamp\n| project insertedTimestamp , Fascia , TOTALE ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Dettaglio su intermediati",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 19 },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in~ (\"paaChiediNumeroAvviso\" , \"paDemandPaymentNotice\", \"paaVerificaRPT\" , \"paaAttivaRPT\" , \"paaInviaRT\" , \"paVerifyPaymentNotice\" , \"paGetPayment\" , \"paSendRT\", \"paGetPaymentV2\", \"paSendRTV2\")\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where faultCode in ($fault)\n| extend intermediario = tostring(substring(stazione, 0, strlen(stazione)-3))\n| where intermediario == \"$sdc\"\n| summarize count=count() by idDominio",
     "querySource": "raw"
    },
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "PA\n| project-rename idDominio=ID_DOMINIO",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Impatti su PSP",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in~ (\"paaChiediNumeroAvviso\" , \"paDemandPaymentNotice\", \"paaVerificaRPT\" , \"paaAttivaRPT\" , \"paaInviaRT\" , \"paVerifyPaymentNotice\" , \"paGetPayment\" , \"paSendRT\", \"paGetPaymentV2\", \"paSendRTV2\")\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where faultCode in ($fault)\n| extend intermediario = tostring(substring(stazione, 0, strlen(stazione)-3))\n| where intermediario == \"$sdc\"\n| summarize sum=count() by psp",
     "querySource": "raw"
    },
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "PSP\n| project-rename psp=ID_PSP",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Dettaglio su metodo",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 19 },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in~ (\"paaChiediNumeroAvviso\" , \"paDemandPaymentNotice\", \"paaVerificaRPT\" , \"paaAttivaRPT\" , \"paaInviaRT\" , \"paVerifyPaymentNotice\" , \"paGetPayment\" , \"paSendRT\", \"paGetPaymentV2\", \"paSendRTV2\")\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where faultCode in ($fault)\n| extend intermediario = tostring(substring(stazione, 0, strlen(stazione)-3))\n| where intermediario == \"$sdc\"\n| summarize sum=count() by tipoEvento",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Dettaglio errori",
   "type": "table",
   "description": "Qui è possibile vedere il dettaglio di ogni singolo evento",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 27 },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| where tipoEvento in~ (\"paaChiediNumeroAvviso\" , \"paDemandPaymentNotice\", \"paaVerificaRPT\" , \"paaAttivaRPT\" , \"paaInviaRT\" , \"paVerifyPaymentNotice\" , \"paGetPayment\" , \"paSendRT\", \"paGetPaymentV2\", \"paSendRTV2\")\n| where faultCode !in~ ('PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE', 'PPT_STAZIONE_INT_PA_TIMEOUT', 'PPT_STAZIONE_INT_PA_SERVIZIO_NONATTIVO')\n| where faultCode in ($fault)\n| extend intermediario = tostring(substring(stazione, 0, strlen(stazione)-3))\n| where intermediario == \"$sdc\"\n| sort by insertedTimestamp\n| extend insertedTimestamp = datetime_local_to_utc(insertedTimestamp, \"Europe/Rome\")",
     "querySource": "raw"
    }
   ]
  }
 ]
}