{
 "title": "[GLOBAL] - Tempi pspNotifyPayment -> sendPaymentOutcome",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "PSP",
    "query": "PSP\n| extend variable = strcat(ID_PSP,\"|\",\"(\", ID_PSP,\") \",RAGIONE_SOCIALE)\n| extend v = strcat(ID_PSP, \" : \", RAGIONE_SOCIALE)\n| sort by RAGIONE_SOCIALE asc\n| project variable"
   },
   { "name": "Campionamento", "query": "1s, 10s, 1m, 10m, 15m, 30m, 1h" }
  ]
 },
 "panels": [
  {
   "title": "Media Tempi Globale",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "//let start=datetime('2022-12-12 00:00:00');\n//let end=datetime('2022-12-12 23:59:59');\nlet start=todatetime(unixtime_milliseconds_todatetime($__from));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to));\nlet pspNP = ReEvent\n| where insertedTimestamp between (start .. end)\n| where categoriaEvento == \"INTERFACCIA\"\n| where tipoEvento in (\"pspNotifyPayment\",\"pspNotifyPaymentV2\")\n| where sottoTipoEvento == \"REQ\"\n| project insertedTimestamp, idDominio, iuv, ccp, psp, paymentToken;\nlet SPO = ReEvent\n| where insertedTimestamp between (start .. end)\n| where categoriaEvento == \"INTERFACCIA\"\n| where tipoEvento in (\"sendPaymentOutcome\", \"sendPaymentOutcomeV2\")\n| where sottoTipoEvento == \"REQ\"\n| extend xml_payload = base64_decode_tostring(payload)\n| extend outcome = extract(\"<outcome>(.*)</outcome>\", 1, xml_payload)\n| project insertedTimestamp, idDominio, iuv, ccp, psp, outcome, stazione, paymentToken;\npspNP\n| join kind=leftouter SPO on paymentToken\n| join kind=inner PSP on $left.psp == $right.ID_PSP\n| join kind=inner PA on $left.idDominio == $right.ID_DOMINIO\n| extend diff_time = datetime_diff(\"second\", insertedTimestamp1, insertedTimestamp)\n| project-rename PA_DESCR=DESCRIZIONE1, PSP_DESCR=DESCRIZIONE\n| project insertedTimestamp, idDominio, iuv, ccp, diff_time, psp, outcome, PSP_DESCR, PA_DESCR, stazione\n| extend PSP_ID_DESCR=strcat(\"(\",psp,\") \",PSP_DESCR)\n| summarize media=avg(diff_time) by bin(insertedTimestamp, $Campionamento), PSP_ID_DESCR\n| sort by insertedTimestamp asc, PSP_ID_DESCR asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Totale pspNotifyPayment",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "//let start=datetime('2022-12-12 00:00:00');\n//let end=datetime('2022-12-12 23:59:59');\nlet start=todatetime(unixtime_milliseconds_todatetime($__from));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to));\nlet pspNP = ReEvent\n| where insertedTimestamp between (start .. end)\n| where categoriaEvento == \"INTERFACCIA\"\n| where tipoEvento == \"pspNotifyPayment\"\n| where sottoTipoEvento == \"REQ\"\n| project insertedTimestamp, idDominio, iuv, ccp, psp;\nlet SPO = ReEvent\n| where insertedTimestamp between (start .. end)\n| where categoriaEvento == \"INTERFACCIA\"\n| where tipoEvento == \"sendPaymentOutcome\"\n| where sottoTipoEvento == \"REQ\"\n| extend xml_payload = base64_decode_tostring(payload)\n| extend outcome = extract(\"<outcome>(.*)</outcome>\", 1, xml_payload)\n| project insertedTimestamp, idDominio, iuv, ccp, psp, outcome, stazione;\npspNP\n| join kind=leftouter SPO on idDominio, iuv, ccp\n| extend diff_time = datetime_diff(\"second\", insertedTimestamp1, insertedTimestamp)\n| project-rename Durata=diff_time\n| extend Pending=case(isnull(insertedTimestamp1), \"Y\",\"N\")\n| project insertedTimestamp, idDominio, iuv, ccp, Durata, psp, outcome, stazione, Pending\n| summarize Total=count() by Pending",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "SPO ricevute a seguito di pspNotifyPayment",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 11 }
   ]
  },
  {
   "title": "pspNotifyPayment in attesa di SPO",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 11 }
   ]
  },
  { "title": "Dettaglio PSP: $PSP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Totale pspNotifyPayment",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "SPO ricevute a seguito di pspNotifyPayment",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "pspNotifyPayment in attesa di SPO",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Tempi di attesa SPO : $PSP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "//let start=datetime('2022-12-12 00:00:00');\n//let end=datetime('2022-12-12 23:59:59');\nlet start=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__from)), \"Europe/Rome\");\nlet end=datetime_utc_to_local(todatetime(unixtime_milliseconds_todatetime($__to)), \"Europe/Rome\");\nlet pspNP = ReEvent\n| where insertedTimestamp between (start .. end)\n| where categoriaEvento == \"INTERFACCIA\"\n| where tipoEvento in (\"pspNotifyPayment\",\"pspNotifyPaymentV2\")\n| where sottoTipoEvento == \"REQ\"\n| where psp == $PSP\n| project insertedTimestamp, idDominio, iuv, ccp, psp, paymentToken;\nlet SPO = ReEvent\n| where insertedTimestamp between (start .. end)\n| where categoriaEvento == \"INTERFACCIA\"\n| where tipoEvento in (\"sendPaymentOutcome\",\"sendPaymentOutcomeV2\")\n| where sottoTipoEvento == \"REQ\"\n| where psp == $PSP\n| extend xml_payload = base64_decode_tostring(payload)\n| extend outcome = extract(\"<outcome>(.*)</outcome>\", 1, xml_payload)\n| project insertedTimestamp, idDominio, iuv, ccp, psp, outcome, stazione, paymentToken;\npspNP\n| join kind=leftouter SPO on paymentToken\n| join kind=inner PSP on $left.psp == $right.ID_PSP\n| join kind=inner PA on $left.idDominio == $right.ID_DOMINIO\n| extend diff_time = datetime_diff(\"millisecond\", insertedTimestamp1, insertedTimestamp)\n| project-rename PA_DESCR=DESCRIZIONE1, PSP_DESCR=DESCRIZIONE, Durata=diff_time\n| extend Pending=case(isnull(insertedTimestamp1), \"Y\",\"N\")\n| extend insertedTimestamp=datetime_local_to_utc(insertedTimestamp, \"Europe/Rome\")\n| project insertedTimestamp, idDominio, iuv, ccp, Durata, psp, outcome, PSP_DESCR, PA_DESCR, stazione, Pending\n| sort by insertedTimestamp asc, PSP_DESCR asc",
     "querySource": "raw"
    }
   ]
  }
 ]
}