{
 "title": "[GLOBAL] - Invio SPO a Token Scaduto",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Intermediario_psp",
    "query": "INTERMEDIARI_PSP\n| extend variable = strcat(ID_INTERMEDIARIO_PSP,\"|\",INTERMEDIARIO_DESCR)\n| extend v = strcat(ID_INTERMEDIARIO_PSP, \" : \", INTERMEDIARIO_DESCR)\n| sort by INTERMEDIARIO_DESCR asc\n| project variable"
   }
  ]
 },
 "panels": [
  {
   "title": "Totale activatePaymentNotice",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to));\nReEvent\n| where insertedTimestamp between (start .. end)\n| project-away payload, sessionId, sessionIdOriginal\n| where tipoEvento in (\"activatePaymentNotice\", \"sendPaymentOutcome\")\n| where sottoTipoEvento == \"REQ\"\n| extend intermediario_psp = substring(canale, 0, strlen(canale)-3)\n| summarize TOTALE=count() by tipoEvento, intermediario_psp, psp\n| join kind=inner INTERMEDIARI_PSP on $left.intermediario_psp == $right.ID_INTERMEDIARIO_PSP\n| join kind=inner PSP on $left.psp == $right.ID_PSP\n| project-away ID_INTERMEDIARIO_PSP, ENABLED, ID_PSP, RAGIONE_SOCIALE, ENABLED1\n| project intermediario_psp, psp, tipoEvento, TOTALE, INTERMEDIARIO_DESCR, DESCRIZIONE\n| where intermediario_psp in ($Intermediario_psp)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Totale SPO",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 8 }
   ]
  },
  {
   "title": "Numero PPT_TOKEN_SCADUTO",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Percentuale",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to));\nlet TotaleSPO = ReEvent\n| where insertedTimestamp between (start .. end)\n| project-away payload, sessionId, sessionIdOriginal\n| where tipoEvento == \"sendPaymentOutcome\"\n| where sottoTipoEvento == \"REQ\"\n| extend intermediario_psp = substring(canale, 0, strlen(canale)-3)\n| summarize TOTALE=count() by tipoEvento, intermediario_psp, psp\n| where intermediario_psp in ($Intermediario_psp)\n| extend multiply = 100;\nlet totaleDuplicati = FAULT_CODE\n| where insertedTimestamp between (start .. end)\n| project-away faultDescription, sessionId , sessionIdOriginal , uniqueId\n| where faultCode == \"PPT_TOKEN_SCADUTO\"\n| extend intermediario_psp = substring(canale, 0, strlen(canale)-3)\n| summarize TOTALE_FAULT=count() by intermediario_psp, psp\n| where intermediario_psp in ($Intermediario_psp);\nTotaleSPO\n| join kind=leftouter totaleDuplicati on $left.intermediario_psp == $right.intermediario_psp, $left.psp == $right.psp\n| extend TOTALE_FAULT=case(isempty(TOTALE_FAULT) == true, 0, TOTALE_FAULT)\n| project tipoEvento, intermediario_psp, psp, TOTALE, multiply, TOTALE_FAULT",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Distribuzione su Intermediari",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Distribuzione su Intermediati",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Dettaglio fault",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "database": "re",
     "expression": {
      "from": { "property": { "name": "ReEvent", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let start=todatetime(unixtime_milliseconds_todatetime($__from + 7200000));\nlet end=todatetime(unixtime_milliseconds_todatetime($__to + 7200000));\nFAULT_CODE\n| where insertedTimestamp between (start .. end)\n| project-away faultDescription, sessionId , sessionIdOriginal , uniqueId\n| where faultCode in (\"PPT_TOKEN_SCADUTO\",\"PPT_TOKEN_SCADUTO_KO\")\n| extend intermediario_psp = substring(canale, 0, strlen(canale)-3)\n| join kind=inner INTERMEDIARI_PSP on $left.intermediario_psp == $right.ID_INTERMEDIARIO_PSP\n| join kind=inner PSP on $left.psp == $right.ID_PSP\n| project-away ENABLED, RAGIONE_SOCIALE, ENABLED1, ID_PSP, ID_INTERMEDIARIO_PSP\n| where intermediario_psp in ($Intermediario_psp)\n| extend insertedTimestamp = datetime_add(\"hour\",-2, insertedTimestamp)",
     "querySource": "raw"
    }
   ]
  }
 ]
}