GRANT SELECT ON TABLE POSITION_TRANSFER  TO offline;
GRANT SELECT ON TABLE RT_VERSAMENTI  TO offline;
GRANT SELECT ON TABLE PM_SESSION_DATA  TO offline;
GRANT SELECT ON TABLE RT  TO offline;
GRANT SELECT ON TABLE RPT  TO offline;
GRANT SELECT ON TABLE RPT_VERSAMENTI  TO offline;
