GRANT SELECT ON ON TABLE POSITION_TRANSFER IN SCHEMA online TO offline;
GRANT SELECT ON ON TABLE RT_VERSAMENTI IN SCHEMA online TO offline;
GRANT SELECT ON ON TABLE PM_SESSION_DATA IN SCHEMA online TO offline;
GRANT SELECT ON ON TABLE RT IN SCHEMA online TO offline;
GRANT SELECT ON ON TABLE RPT IN SCHEMA online TO offline;
GRANT SELECT ON ON TABLE RPT_VERSAMENTI IN SCHEMA online TO offline;
