{
  "openapi": "3.0.0",
  "info": {
    "version": "0.0.1",
    "title": "Pagopa eCommerce services for app IO with payment wallet",
    "description": "API's exposed from eCommerce services to app IO to allow pagoPA payment with payment wallet.",
    "contact": {
      "name": "pagoPA - Touchpoints team"
    }
  },
  "tags": [
    {
      "name": "ecommerce-methods-handler",
      "description": "Api's for retrieve payment methods for performing transactions payment",
    },
  ],
  "servers": [
    {
      "url": "https://${host}"
    }
  ],
  "externalDocs": {
    "url": "https://pagopa.atlassian.net/wiki/spaces/I/pages/492339720/pagoPA+eCommerce+Design+Review",
    "description": "Design review"
  },
  "paths": {
  "/payment-methods": {
    "post": {
        "tags": [
          "ecommerce-methods-handler"
        ],
        "operationId": "getAllPaymentMethods",
        "summary": "Retrieve all Payment Methods (by filter)",
        "description": "GET with body payload - no resources created: API for retrieve payment method using the request query parameter filters",
        "security": [
          {
            "pagoPAPlatformSessionToken": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PaymentMethodsRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Payment method successfully retrieved",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PaymentMethodsResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemJson"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemJson"
                }
              }
            }
          },
          "500": {
            "description": "Service unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemJson"
                }
              }
            }
          }
        }
      }
    },
  },
  "components": {
    "schemas": {
      "ProblemJson": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "format": "uri",
            "description": "An absolute URI that identifies the problem type. When dereferenced,\nit SHOULD provide human-readable documentation for the problem type\n(e.g., using HTML).",
            "default": "about:blank",
            "example": "https://example.com/problem/constraint-violation"
          },
          "title": {
            "type": "string",
            "description": "A short, summary of the problem type. Written in english and readable\nfor engineers (usually not suited for non technical stakeholders and\nnot localized); example: Service Unavailable"
          },
          "status": {
            "$ref": "#/components/schemas/HttpStatusCode"
          },
          "detail": {
            "type": "string",
            "description": "A human readable explanation specific to this occurrence of the\nproblem.",
            "example": "There was an error processing the request"
          },
          "instance": {
            "type": "string",
            "format": "uri",
            "description": "An absolute URI that identifies the specific occurrence of the problem.\nIt may or may not yield further information if dereferenced."
          }
        }
      },
      "HttpStatusCode": {
        "type": "integer",
        "format": "int32",
        "description": "The HTTP status code generated by the origin server for this occurrence\nof the problem.",
        "minimum": 100,
        "maximum": 600,
        "exclusiveMaximum": true,
        "example": 500
      },
      "PaymentMethodsRequest": {
        "required": [
          "paymentNotice",
          "totalAmount",
          "userTouchpoint"
        ],
        "type": "object",
        "properties": {
          "userTouchpoint": {
            "type": "string",
            "enum": [
              "IO",
              "CHECKOUT",
              "CHECKOUT_CART"
            ]
          },
          "userDevice": {
            "type": "string",
            "enum": [
              "IOS",
              "ANDROID",
              "WEB",
              "SAFARI"
            ]
          },
          "bin": {
            "type": "string"
          },
          "totalAmount": {
            "type": "integer",
            "format": "int64"
          },
          "paymentNotice": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/PaymentNoticeItem"
            }
          },
          "allCCp": {
            "type": "boolean"
          },
          "targetKey": {
            "type": "string"
          }
        }
      },
      "PaymentNoticeItem": {
        "required": [
          "paymentAmount",
          "primaryCreditorInstitution"
        ],
        "type": "object",
        "properties": {
          "paymentAmount": {
            "type": "integer",
            "format": "int64"
          },
          "primaryCreditorInstitution": {
            "type": "string"
          },
          "transferList": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/TransferListItem"
            }
          }
        }
      },
      "FeeRange": {
        "required": [
          "max",
          "min"
        ],
        "type": "object",
        "properties": {
          "min": {
            "type": "integer",
            "format": "int64"
          },
          "max": {
            "type": "integer",
            "format": "int64"
          }
        }
      },
      "PaymentMethodResponse": {
        "required": [
          "description",
          "feeRange",
          "paymentTypeCode",
          "methodManagement",
          "name",
          "paymentMethodAsset",
          "id",
          "paymentMethodTypes",
          "status",
          "validityDateFrom"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "description": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "status": {
            "type": "string",
            "enum": [
              "ENABLED",
              "DISABLED",
              "MAINTENANCE"
            ]
          },
          "validityDateFrom": {
            "type": "string",
            "format": "date"
          },
          "paymentTypeCode": {
            "type": "string",
            "enum": [
              "CP",
              "MYBK",
              "BPAY",
              "PPAL",
              "RPIC",
              "RBPS",
              "SATY",
              "APPL",
              "RICO",
              "RBPB",
              "RBPP",
              "RBPR",
              "GOOG",
              "KLRN"
            ]
          },
          "paymentMethodTypes": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "CARTE",
                "CONTO",
                "APP"
              ]
            }
          },
          "feeRange": {
            "$ref": "#/components/schemas/FeeRange"
          },
          "paymentMethodAsset": {
            "type": "string"
          },
          "methodManagement": {
            "type": "string",
            "enum": [
              "ONBOARDABLE",
              "ONBOARDABLE_ONLY",
              "NOT_ONBOARDABLE",
              "REDIRECT"
            ]
          },
          "disabledReason": {
            "type": "string",
            "enum": [
              "AMOUNT_OUT_OF_BOUND",
              "MAINTENANCE_IN_PROGRESS",
              "METHOD_DISABLED",
              "NOT_YET_VALID",
              "TARGET_PREVIEW",
              "NO_BUNDLE_AVAILABLE"
            ]
          },
          "paymentMethodsBrandAssets": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "metadata": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          }
        }
      },
      "PaymentMethodsResponse": {
        "required": [
          "paymentMethods"
        ],
        "type": "object",
        "properties": {
          "paymentMethods": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/PaymentMethodResponse"
            }
          }
        }
      },
      "TransferListItem": {
        "description": "Transfer list item",
        "type": "object",
        "properties": {
          "creditorInstitution": {
            "description": "Creditor institution",
            "type": "string"
          },
          "digitalStamp": {
            "description": "Boolean value indicating if there is digital stamp",
            "type": "boolean"
          },
          "transferCategory": {
            "description": "Transfer category",
            "type": "string"
          }
        }
      }
    },
    "requestBodies": {
      "PaymentMethodsRequest": {
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/PaymentMethodsRequest"
            }
          }
        }
      }
    },
    "securitySchemes": {
      "pagoPAPlatformSessionToken": {
        "type": "http",
        "scheme": "bearer",
        "description": "JWT session token taken according to pagoPA platform auth for IO app"
      }
    }
  }
}
