apiVersion: batch/v1
kind: CronJob
metadata:
  name: debezium-health-checker-cron
  namespace: ${namespace}
spec:
  schedule: "*/5 * * * *"  # Runs every 5 minutes
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        metadata:
          labels:
            app: debezium-health-checker-cron
        spec:
          containers:
          - name: debezium-health-checker
            image: public.ecr.aws/docker/library/alpine:3.23.2@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62
            command:
              - /bin/sh
              - -c
              - |
                apk add --no-cache curl bash &&
                sh /scripts/check_kafka_connect.sh
            volumeMounts:
            - name: script-volume
              mountPath: /scripts
          restartPolicy: OnFailure
          volumes:
          - name: script-volume
            configMap:
              name: debezium-health-checker-script
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: node_type
                        operator: In
                        values:
                          - user
