apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: debezium-connect-cluster-network-policy
  namespace: ${namespace}
spec:
  podSelector:
    matchLabels:
      strimzi.io/name: debezium-connect-cluster-connect
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: nginx-ingress
              app.kubernetes.io/component: controller
        - podSelector:
            matchLabels:
              strimzi.io/cluster: debezium-connect-cluster
              strimzi.io/kind: KafkaConnect
              strimzi.io/name: debezium-connect-cluster-connect
        - podSelector:
            matchLabels:
              strimzi.io/kind: cluster-operator
        - podSelector:
            matchLabels:
              app: debezium-health-checker-cron
      ports:
        - protocol: TCP
          port: 8083
