apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-connector-postgres
  namespace: ${namespace}
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: ${tasks_max}
  config:
    connector.class: "io.debezium.connector.postgresql.PostgresConnector"
    key.converter: "org.apache.kafka.connect.json.JsonConverter"
    key.converter.schemas.enable: false
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter.schemas.enable: false
    tasks.max: ${tasks_max}
    database.hostname: ${postgres_hostname}
    database.port:  ${postgres_port}
    database.user: ${postgres_username}
    database.password: ${postgres_password}
    database.dbname: ${postgres_db_name}
    topic.prefix: ${postgres_topic_prefix}
    schema.include.list: "apd"
    table.include.list: "apd.payment_option,apd.payment_position,apd.transfer"
    plugin.name: "pgoutput"
    snapshot.max.threads: ${max_threads}
    publication.autocreate.mode: "disabled" # shall be create before 
    # publication.autocreate.mode: "filtered"  # create it
