apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-connector-postgres
  namespace: ${namespace}
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: ${tasks_max}
  config:
    key.converter: "org.apache.kafka.connect.json.JsonConverter"
    key.converter.schemas.enable: false
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter.schemas.enable: false
    database.hostname: ${postgres_hostname}
    database.port:  ${postgres_port}
    database.user: ${postgres_username}
    database.password: ${postgres_password}
    database.dbname: ${postgres_db_name}
    topic.prefix: ${postgres_topic_prefix}
    schema.include.list: "apd"
    table.include.list: "apd.payment_option,apd.payment_position,apd.transfer"
    plugin.name: "pgoutput"
    snapshot.max.threads: ${max_threads}
    publication.autocreate.mode: "disabled" # shall be create before

    transforms: "filterArchived"
    transforms.filterArchived.type: "io.debezium.transforms.Filter"
    transforms.filterArchived.language: "jsr223.groovy"

    # Groovy filter logic:
    # 1. If value is null (Tombstone): keep
    # 2. If it is a DELETE (d): keep ONLY if before.archived is false
    # 3. If it is INSERT/UPDATE: keep ONLY if after.archived is false
    transforms.filterArchived.condition: "value == null ? true : (value.op == 'd' ? value.before?.archived != true : value.after?.archived != true)"