apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: debezium-connect-cluster
  namespace: ${namespace}
spec:
  zookeeper:
    replicas: ${zookeeper_replicas}
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: INFO
    resources:
      requests:
        memory: "${zookeeper_request_memory}"
        cpu: "${zookeeper_request_cpu}"
      limits:
        memory: "${zookeeper_limits_memory}"
        cpu: "${zookeeper_limits_cpu}"
    jvmOptions:
      -Xms: ${zookeeper_jvm_xms}
      -Xmx: ${zookeeper_jvm_xmx}
    storage:
      type: persistent-claim
      size: ${zookeeper_storage_size}

