ALTER DEFAULT PRIVILEGES FOR ROLE partition IN SCHEMA online
GRANT ALL ON TABLES TO partition;
ALTER DEFAULT PRIVILEGES FOR ROLE partition IN SCHEMA online
GRANT ALL ON SEQUENCES TO partition;
ALTER DEFAULT PRIVILEGES FOR ROLE partition IN SCHEMA online
GRANT EXECUTE ON FUNCTIONS TO partition;
ALTER DEFAULT PRIVILEGES FOR ROLE partition IN SCHEMA online
GRANT USAGE ON TYPES TO partition;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "partition";
ALTER DEFAULT PRIVILEGES IN SCHEMA online GRANT ALL ON TABLES TO "partition";
ALTER DEFAULT PRIVILEGES IN SCHEMA re GRANT ALL ON TABLES TO "partition";
ALTER DEFAULT PRIVILEGES IN SCHEMA wfesp GRANT ALL ON TABLES TO "partition";
ALTER DEFAULT PRIVILEGES IN SCHEMA offline GRANT ALL ON TABLES TO "partition";
ALTER DEFAULT PRIVILEGES FOR ROLE partition IN SCHEMA partition
GRANT ALL ON SEQUENCES TO partition;
ALTER DEFAULT PRIVILEGES FOR ROLE partition IN SCHEMA partition
GRANT EXECUTE ON FUNCTIONS TO partition;
ALTER DEFAULT PRIVILEGES FOR ROLE partition IN SCHEMA partition
GRANT USAGE ON TYPES TO partition;
GRANT ALL ON SCHEMA public TO partition;
ALTER DEFAULT PRIVILEGES FOR ROLE partition IN SCHEMA public
GRANT ALL ON SEQUENCES TO partition;
ALTER DEFAULT PRIVILEGES FOR ROLE partition IN SCHEMA public
GRANT EXECUTE ON FUNCTIONS TO partition;
ALTER DEFAULT PRIVILEGES FOR ROLE partition IN SCHEMA public
GRANT USAGE ON TYPES TO partition;
ALTER DEFAULT PRIVILEGES FOR ROLE partition IN SCHEMA partition
GRANT ALL ON TABLES TO azureuser;
ALTER DEFAULT PRIVILEGES FOR ROLE partition IN SCHEMA partition
GRANT ALL ON SEQUENCES TO azureuser;
ALTER DEFAULT PRIVILEGES FOR ROLE partition IN SCHEMA partition
GRANT EXECUTE ON FUNCTIONS TO azureuser;
ALTER DEFAULT PRIVILEGES FOR ROLE partition IN SCHEMA partition
GRANT USAGE ON TYPES TO azureuser;
GRANT ALL ON TABLE partition.tab_part TO azureuser;
GRANT TRUNCATE, UPDATE, INSERT, TRIGGER, DELETE, REFERENCES, SELECT ON TABLE "partition".pg_log TO azureuser;
GRANT SELECT ON ALL TABLES IN SCHEMA online,offline,re,wfesp TO partition ;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA online,offline,re,wfesp TO partition ;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA online,offline,re,wfesp TO partition ;
