GRANT CREATE, USAGE ON SCHEMA online TO partition;

GRANT ALL ON ALL TABLES IN SCHEMA online TO partition;
GRANT ALL ON ALL SEQUENCES IN SCHEMA online TO partition;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA online TO partition;

GRANT ALL ON ALL TABLES IN SCHEMA partition TO partition;
GRANT ALL ON ALL SEQUENCES IN SCHEMA partition TO partition;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA partition TO partition;

GRANT ALL ON ALL TABLES IN SCHEMA partition TO azureuser;
GRANT ALL ON ALL SEQUENCES IN SCHEMA partition TO azureuser;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA partition TO azureuser;

GRANT ALL ON ALL TABLES IN SCHEMA re TO partition;
GRANT ALL ON ALL SEQUENCES IN SCHEMA re TO partition;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA re TO partition;

GRANT ALL ON ALL TABLES IN SCHEMA re TO azureuser;
GRANT ALL ON ALL SEQUENCES IN SCHEMA re TO azureuser;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA re TO azureuser;

GRANT ALL ON ALL TABLES IN SCHEMA wfesp TO partition;
GRANT ALL ON ALL SEQUENCES IN SCHEMA wfesp TO partition;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA wfesp TO partition;

GRANT ALL ON ALL TABLES IN SCHEMA wfesp TO azureuser;
GRANT ALL ON ALL SEQUENCES IN SCHEMA wfesp TO azureuser;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA wfesp TO azureuser;

GRANT ALL ON ALL TABLES IN SCHEMA offline TO partition;
GRANT ALL ON ALL SEQUENCES IN SCHEMA offline TO partition;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA offline TO partition;

GRANT ALL ON ALL TABLES IN SCHEMA offline TO azureuser;
GRANT ALL ON ALL SEQUENCES IN SCHEMA offline TO azureuser;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA offline TO azureuser;


GRANT ALL ON TABLE partition.tab_part TO azureuser;
GRANT TRUNCATE, UPDATE, INSERT, TRIGGER, DELETE, REFERENCES, SELECT ON TABLE "partition".pg_log TO azureuser;
GRANT SELECT ON ALL TABLES IN SCHEMA online,offline,re,wfesp TO partition ;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA online,offline,re,wfesp TO partition ;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA online,offline,re,wfesp TO partition ;
