pr: none
trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: env
    displayName: deploy environment
    type: string
    default: dev
    values:
      - dev
      - uat
      - prd

variables:
  ${{ if eq(parameters.env, 'dev') }}:
    AZURE_SERVICE_CONNECTION: '$(TF_AZURE_SERVICE_CONNECTION_APPLY_NAME_DEV)'
    METABASE_KEY_VAULT_NAME: 'pagopa-d-itn-core-kv'
    poolImage: 'pagopa-dev-linux-infra'
    ENV: 'd'
  ${{ elseif eq(parameters.env, 'uat') }}:
    AZURE_SERVICE_CONNECTION: '$(TF_AZURE_SERVICE_CONNECTION_APPLY_NAME_UAT)'
    METABASE_KEY_VAULT_NAME: 'pagopa-u-itn-core-kv'
    poolImage: 'pagopa-uat-linux-infra'
    ENV: 'u'
  ${{ elseif eq(parameters.env, 'prd') }}:
    AZURE_SERVICE_CONNECTION: '$(TF_AZURE_SERVICE_CONNECTION_APPLY_NAME_PROD)'
    METABASE_KEY_VAULT_NAME: 'pagopa-p-itn-core-kv'
    poolImage: 'pagopa-prod-linux-infra'
    ENV: 'p'




stages:
  - stage: get_read_user_credentials
    displayName: "Get read user credentials"
    jobs:
      - job: get_credentials
        pool: $(poolImage)
        displayName: "Get credentials job"
        steps:
          - task: AzureKeyVault@2
            displayName: "Get read user password from key vault"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              keyVaultName: $(METABASE_KEY_VAULT_NAME)
              secretsFilter: 'metabase-reader-login,metabase-reader-password'
          - script: |
              echo "##vso[task.setvariable variable=READ_USER_PASSWORD;isOutput=true]$(metabase-reader-password)"
              echo "##vso[task.setvariable variable=READ_USER_LOGIN;isOutput=true]$(metabase-reader-login)"
            displayName: "Set read user password as pipeline variable"
            name: credentials
            env:
              metabase-password: $(metabase-password)
      # replicate this for each database
      - job: create_user_nodo
        dependsOn: get_credentials
        pool: $(poolImage)
        displayName: "Create read user in nodo db"
        variables:
          READ_USER_LOGIN: $[ dependencies.get_credentials.outputs['credentials.READ_USER_LOGIN'] ]
          READ_USER_PASSWORD: $[ dependencies.get_credentials.outputs['credentials.READ_USER_PASSWORD'] ]
        steps:
          - template: ./templates/db-readonly-user-create.yml
            parameters:
              DATABASE_NAME: 'postgres'
              DB_HOST: 'pagopa-${{ variables.ENV }}-weu-nodo-flexible-postgresql'
              USERNAME: $(READ_USER_LOGIN)
              PASSWORD: $(READ_USER_PASSWORD)
              KEY_VAULT_NAME: "pagopa-${{ variables.ENV }}-nodo-kv"
              ADMIN_LOGIN_KEY: "db-administrator-login"
              ADMIN_PWD_KEY: "db-administrator-login-password"
              SERVICE_CONNECTION: $(AZURE_SERVICE_CONNECTION)



