trigger: none

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v6.9.0
      endpoint: "io-azure-devops-github-ro"
    - repository: self
      type: git
      trigger:
        branches:
          include:
            - refs/heads/alert-suspend-cron-55FG123SD-*

variables:
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/alert-suspend-cron-') }}:
    branchName: $[ replace(variables['Build.SourceBranch'], 'refs/heads/', '') ]
    alertKey: $[ split(variables['branchName'], '-')[3] ]
    timestamp: $[ split(variables['branchName'], '-')[4] ]
    env: $[ split(variables['branchName'], '-')[5] ]

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: SuspendCronJobs
    displayName: 'Suspend Nodo Cron Jobs'
    steps:
      - template: templates/azure-kubeconfig-generator/template.yaml@templates
        parameters:
          AZURE_SERVICE_CONNECTION_NAME: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_DEV)'
          AKS_NAME: '$(TF_AKS_DEV_NAME)'
          AKS_API_SERVER_URL: '$(TF_DEV_AKS_APISERVER_URL)'
          AKS_AZURE_DEVOPS_SA_CA_CRT: '$(TF_DEV_AKS_AZURE_DEVOPS_SA_CACRT)'
          AKS_AZURE_DEVOPS_SA_TOKEN: '$(TF_DEV_AKS_AZURE_DEVOPS_SA_TOKEN)'

      - task: AzureCLI@2
        inputs:
          azureSubscription: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_DEV)'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            kubectl get cronjobs -n nodo-cron
