{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "Notification API",
    "description": "API to support notifications"
  },
  "host": "https://${hostname}",
  "basePath": "/notifications",
  "schemes": [
    "https"
  ],
  "paths": {
    "/emails": {
      "x-swagger-router-controller": "emailController",
      "post": {
        "operationId": "sendNotificationEmail",
        "summary": "New Notification email",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "schema": {
              "$ref": "#/definitions/NotificationEmailRequest"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Email notification started",
            "schema": {
              "$ref": "#/definitions/NotificationEmailResponse"
            },
            "examples": {
              "application/json": {
                "importoSingoloVersamento": 200
              }
            }
          },
          "400": {
            "description": "Invalid input",
            "schema": {
              "$ref": "#/definitions/ProblemJson"
            }
          },
          "500": {
            "description": "Generic server error",
            "schema": {
              "$ref": "#/definitions/ProblemJson"
            }
          }
        }
      }
    },
    "/info": {
      "x-swagger-router-controller": "infoController",
      "get": {
        "operationId": "getInfo",
        "summary": "Get service information",
        "responses": {
          "200": {
            "description": "Service information",
            "schema": {
              "$ref": "#/definitions/InfoResponse"
            }
          },
          "500": {
            "description": "Generic server error",
            "schema": {
              "$ref": "#/definitions/ProblemJson"
            }
          }
        }
      }
    },
    "/health": {
      "x-swagger-router-controller": "healthController",
      "get": {
        "operationId": "getHealth",
        "summary": "Get service health",
        "responses": {
          "200": {
            "description": "The service is healthy",
            "schema": {
              "$ref": "#/definitions/HealthResponse"
            }
          },
          "500": {
            "description": "Service is unhealthy",
            "schema": {
              "$ref": "#/definitions/ProblemJson"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "NotificationEmailRequest": {
      "type": "object",
      "properties": {
        "from": {
          "type": "string"
        },
        "to": {
          "type": "string"
        },
        "templateId": {
          "type": "string"
        },
        "pspName": {
          "type": "string"
        },
        "amount": {
          "type": "integer"
        }
      },
      "required": [
        "from",
        "to",
        "templateId",
        "transactionId",
        "pspName",
        "amount"
      ]
    },
    "NotificationEmailResponse": {
      "type": "object",
      "properties": {
        "outcome": {
          "type": "string"
        }
      }
    },
    "HttpStatusCode": {
      "type": "integer",
      "format": "int32",
      "description": "The HTTP status code generated by the origin server for this occurrence\nof the problem.",
      "minimum": 100,
      "maximum": 600,
      "exclusiveMaximum": true,
      "example": 200
    },
    "InfoResponse": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "HealthResponse": {
      "type": "object",
      "properties": {
        "sentLast24Hours": {
          "type": "number"
        }
      }
    },
    "ProblemJson": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "format": "uri",
          "description": "An absolute URI that identifies the problem type. When dereferenced,\nit SHOULD provide human-readable documentation for the problem type\n(e.g., using HTML).",
          "default": "about:blank",
          "example": "https://example.com/problem/constraint-violation"
        },
        "title": {
          "type": "string",
          "description": "A short, summary of the problem type. Written in english and readable\nfor engineers (usually not suited for non technical stakeholders and\nnot localized); example: Service Unavailable"
        },
        "status": {
          "$ref": "#/definitions/HttpStatusCode"
        },
        "detail": {
          "type": "string",
          "description": "A human readable explanation specific to this occurrence of the\nproblem.",
          "example": "There was an error processing the request"
        },
        "instance": {
          "type": "string",
          "format": "uri",
          "description": "An absolute URI that identifies the specific occurrence of the problem.\nIt may or may not yield further information if dereferenced."
        }
      }
    }
  }
}
