{
 "title": "Akka Dispatchers",
 "tags": [ "nodo" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Applications",
    "query": "label_values(akka_dispatcher_parallelism{namespace=~\"nodo|nodo-cron\"}, application)"
   },
   {
    "name": "Servers",
    "query": "label_values(akka_dispatcher_parallelism{application=~\"$Applications\"}, host)"
   },
   {
    "name": "ActorSystems",
    "query": "label_values(akka_dispatcher_parallelism{host=~\"$Servers\", application=~\"$Applications\"}, actor_system)"
   },
   {
    "name": "Dispatchers",
    "query": "label_values(akka_dispatcher_pool_size{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\"}, dispatcher)"
   },
   {
    "name": "Quantile",
    "query": "label_values(akka_dispatcher_queue_time_ns, quantile)"
   }
  ]
 },
 "panels": [
  { "title": "$Applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queued Tasks",
   "type": "graph",
   "description": "The number of tasks waiting to be processed. High queue sizes may be indicative of thread starvation issues.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "akka_dispatcher_queued_tasks{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", dispatcher=~\"$Dispatchers\"}",
     "legendFormat": "{{host}} / {{actor_system}} / {{dispatcher}}"
    }
   ]
  },
  {
   "title": "Processed Tasks",
   "type": "graph",
   "description": "How many tasks are being processed right now.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "akka_dispatcher_processed_tasks{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", dispatcher=~\"$Dispatchers\"}",
     "legendFormat": "{{host}} / {{actor_system}} / {{dispatcher}}"
    }
   ]
  },
  {
   "title": "Pool Size",
   "type": "graph",
   "description": "The current size of the thread pool.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "akka_dispatcher_pool_size{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", dispatcher=~\"$Dispatchers\"}",
     "legendFormat": "{{host}} / {{actor_system}} / {{dispatcher}}"
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "graph",
   "description": "An estimate of the number of threads running or stealing tasks.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "akka_dispatcher_active_threads{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", dispatcher=~\"$Dispatchers\"}",
     "legendFormat": "{{host}} / {{actor_system}} / {{dispatcher}}"
    }
   ]
  },
  {
   "title": "Running Threads",
   "type": "graph",
   "description": "An estimate of the number of threads not blocked in managed synchronization.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "akka_dispatcher_running_threads{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", dispatcher=~\"$Dispatchers\"}",
     "legendFormat": "{{host}} / {{actor_system}} / {{dispatcher}}"
    }
   ]
  },
  {
   "title": "Parallelism",
   "type": "graph",
   "description": "The parallelism setting.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "akka_dispatcher_parallelism{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", dispatcher=~\"$Dispatchers\"}",
     "legendFormat": "{{host}} / {{actor_system}} / {{dispatcher}}"
    }
   ]
  }
 ]
}