{
 "title": "Akka HTTP and Play Servers",
 "tags": [ "nodo" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Applications",
    "query": "label_values(akka_http_http_server_connections_total{namespace=~\"nodo|nodo-cron\"}, application)"
   },
   {
    "name": "Servers",
    "query": "label_values(akka_http_http_server_connections_total{application=~\"$Applications\"}, host)"
   },
   {
    "name": "ActorSystems",
    "query": "label_values(akka_http_http_server_connections_total{host=~\"$Servers\", application=~\"$Applications\"}, actor_system)"
   },
   {
    "name": "HttpServers",
    "query": "label_values(akka_http_http_server_connections_total{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\"}, http_server)"
   },
   {
    "name": "HttpPorts",
    "query": "label_values(akka_http_http_server_connections_total{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\"}, http_server)"
   },
   {
    "name": "Quantile",
    "query": "label_values(akka_http_http_server_response_time_2xx_ns{host=~\"$Servers\", application=~\"$Applications\"}, quantile)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests/Responses: 1 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops", "label": "messages/second" }
   ],
   "targets": [
    {
     "expr": "irate(akka_http_http_server_requests_total{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", http_server=~\"$HttpServers:.*\", http_server=~\".*:$HttpPorts\"}[1m])",
     "legendFormat": "{{application}} / {{host}} / {{http_server}} / requests"
    },
    {
     "expr": "irate(akka_http_http_server_responses_total{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", http_server=~\"$HttpServers:.*\", http_server=~\".*:$HttpPorts\"}[1m])",
     "legendFormat": "{{application}} / {{host}} / {{http_server}} / responses"
    }
   ]
  },
  {
   "title": "Requests/Responses: 15 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops", "label": "messages/second" }
   ],
   "targets": [
    {
     "expr": "irate(akka_http_http_server_requests_total{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", http_server=~\"$HttpServers:.*\", http_server=~\".*:$HttpPorts\"}[15m])",
     "legendFormat": "{{application}} / {{host}} / {{http_server}} / requests"
    },
    {
     "expr": "irate(akka_http_http_server_responses_total{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", http_server=~\"$HttpServers:.*\", http_server=~\".*:$HttpPorts\"}[15m])",
     "legendFormat": "{{application}} / {{host}} / {{http_server}} / responses"
    }
   ]
  },
  {
   "title": "Connections: 1 min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops", "label": "connections/second" }
   ],
   "targets": [
    {
     "expr": "irate(akka_http_http_server_connections_total{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", http_server=~\"$HttpServers:.*\", http_server=~\".*:$HttpPorts\"}[1m])",
     "legendFormat": "{{application}} / {{host}} / {{http_server}}"
    }
   ]
  },
  {
   "title": "Response Rate 2xx: 1 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ops", "label": "messages/second" }
   ],
   "targets": [
    {
     "expr": "irate(akka_http_http_server_responses_2xx_total{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", http_server=~\"$HttpServers:.*\", http_server=~\".*:$HttpPorts\"}[1m])",
     "legendFormat": "{{application}} / {{host}} / {{http_server}}"
    }
   ]
  },
  {
   "title": "Response Time 2xx ($Quantile quantile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "akka_http_http_server_response_time_2xx_ns{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", http_server=~\"$HttpServers:.*\", http_server=~\".*:$HttpPorts\", quantile=~\"$Quantile\"}",
     "legendFormat": "{{application}} / {{host}} / {{http_server}}"
    }
   ]
  },
  {
   "title": "Response Rate 4xx: 1 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ops", "label": "messages/second" }
   ],
   "targets": [
    {
     "expr": "irate(akka_http_http_server_responses_4xx_total{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", http_server=~\"$HttpServers:.*\", http_server=~\".*:$HttpPorts\"}[1m])",
     "legendFormat": "{{application}} / {{host}} / {{http_server}}"
    }
   ]
  },
  {
   "title": "Response Time 4xx ($Quantile quantile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "akka_http_http_server_response_time_4xx_ns{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", http_server=~\"$HttpServers:.*\", http_server=~\".*:$HttpPorts\", quantile=~\"$Quantile\"}",
     "legendFormat": "{{application}} / {{host}} / {{http_server}}"
    }
   ]
  },
  {
   "title": "Response Rate 5xx: 1 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ops", "label": "messages/second" }
   ],
   "targets": [
    {
     "expr": "irate(akka_http_http_server_responses_5xx_total{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", http_server=~\"$HttpServers:.*\", http_server=~\".*:$HttpPorts\"}[1m])",
     "legendFormat": "{{application}} / {{host}} / {{http_server}}"
    }
   ]
  },
  {
   "title": "Response Time 5xx ($Quantile quantile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "akka_http_http_server_response_time_5xx_ns{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", http_server=~\"$HttpServers:.*\", http_server=~\".*:$HttpPorts\", quantile=~\"$Quantile\"}",
     "legendFormat": "{{application}} / {{host}} / {{http_server}}"
    }
   ]
  }
 ]
}