{
 "title": "Akka Actors",
 "tags": [ "nodo" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(akka_actor_running_actors{namespace=~\"nodo|nodo-cron\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(akka_actor_running_actors{namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "dispatcher",
    "label": "Dispatchers",
    "query": {
     "query": "label_values(akka_actor_running_actors{namespace=\"$namespace\",pod=~\"$pod\"}, dispatcher)"
    }
   },
   {
    "name": "actor",
    "label": "Actors",
    "query": {
     "query": "label_values(akka_actor_running_actors{namespace=\"$namespace\",pod=~\"$pod\"}, actor)"
    }
   },
   {
    "name": "Quantile",
    "query": {
     "query": "label_values(akka_actor_mailbox_size, quantile)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running actors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "akka_actor_running_actors{namespace=~\"$namespace\", pod=~\"$pod\",dispatcher=~\"$dispatcher\", actor=~\"$actor\"}",
     "legendFormat": "{{host}} / {{dispatcher}} / {{actor}}"
    }
   ]
  },
  {
   "title": "Sent messages: 1min rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ops", "label": "messages/second" }
   ],
   "targets": [
    {
     "expr": "irate(akka_message_sent_messages_total{namespace=~\"$namespace\", pod=~\"$pod\",dispatcher=~\"$dispatcher\", actor=~\"$actor\"}[1m])",
     "legendFormat": "{{host}} / {{dispatcher}} / {{actor}}"
    }
   ]
  },
  {
   "title": "Dropped messages: 1min rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops", "label": "messages/second" }
   ],
   "targets": [
    {
     "expr": "irate(akka_actor_dropped_messages_total{namespace=~\"$namespace\", pod=~\"$pod\",dispatcher=~\"$dispatcher\", actor=~\"$actor\"}[1m])",
     "legendFormat": "{{host}} / {{dispatcher}} / {{actor}}"
    }
   ]
  },
  {
   "title": "Processed messages: 1min rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ops", "label": "messages/second" }
   ],
   "targets": [
    {
     "expr": "irate(akka_message_processed_messages_total{namespace=~\"$namespace\", pod=~\"$pod\",dispatcher=~\"$dispatcher\", actor=~\"$actor\"}[1m])",
     "legendFormat": "{{host}} / {{dispatcher}} / {{actor}} "
    }
   ]
  },
  {
   "title": "Mailbox time ($Quantile quantile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "akka_actor_mailbox_time_ns{namespace=~\"$namespace\", pod=~\"$pod\",dispatcher=~\"$dispatcher\", actor=~\"$actor\", quantile=~\"$Quantile\"}",
     "legendFormat": "{{host}} / {{dispatcher}} / {{actor}}"
    }
   ]
  },
  {
   "title": "Processing time ($Quantile quantile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "akka_message_processing_time_ns{namespace=~\"$namespace\", pod=~\"$pod\",dispatcher=~\"$dispatcher\", actor=~\"$actor\", quantile=~\"$Quantile\"}",
     "legendFormat": "{{host}} / {{dispatcher}} / {{actor}} "
    }
   ]
  },
  {
   "title": "Mailbox size ($Quantile quantile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "akka_actor_mailbox_size{namespace=~\"$namespace\", pod=~\"$pod\",dispatcher=~\"$dispatcher\", actor=~\"$actor\", quantile=~\"$Quantile\"}",
     "legendFormat": "{{host}} / {{dispatcher}} / {{actor}}"
    }
   ]
  },
  {
   "title": "Stash size ($Quantile quantile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "akka_actor_stash_size{namespace=~\"$namespace\", pod=~\"$pod\",dispatcher=~\"$dispatcher\", actor=~\"$actor\", quantile=~\"$Quantile\"}",
     "legendFormat": "{{host}} / {{dispatcher}} / {{actor}}"
    }
   ]
  }
 ]
}