{
 "title": "JMX prometheus exporter",
 "description": "Complete dashboard using metrics from prometheus JMX exporter, with drill down per service > pod",
 "tags": [ "JVM" ],
 "time": { "from": "2023-07-25T07:40:16.830Z", "to": "2023-07-25T23:40:16.830Z" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "service", "label": "service", "query": { "query": "label_values(service)" } },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(jvm_info{service=\"$service\"},pod)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(jvm_info{service=\"$service\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_bytes_used{area=\"heap\",service=\"$service\",pod=\"$pod\"})*100) / sum(jvm_memory_bytes_max{area=\"heap\",service=\"$service\",pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{service=\"$service\"})*1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_info{}" }
   ]
  },
  {
   "title": "CPU Usage vs Throttling Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "cpu cores" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,pod) (rate(container_cpu_usage_seconds_total{pod=~\"$pod\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "CPU Cores Usage {{pod}}"
    },
    {
     "expr": "sum by (namespace,pod) ((container_cpu_cfs_throttled_periods_total{pod=~\"$pod\",namespace=\"$namespace\"} / container_cpu_cfs_periods_total{pod=~\"$pod\",namespace=\"$namespace\"}) * 100)",
     "legendFormat": "Throttle Percent {{pod}}"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",service=\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Used {{pod}}"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",service=\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Max {{pod}}"
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",service=\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Used  {{pod}}"
    }
   ]
  },
  {
   "title": "G1 Eden Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{service=\"$service\", pool=\"G1 Eden Space\",pod=~\"$pod\"}",
     "legendFormat": "Max  {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{service=\"$service\", pool=\"G1 Eden Space\",pod=~\"$pod\"}",
     "legendFormat": "Used  {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{service=\"$service\", pool=\"G1 Eden Space\",pod=~\"$pod\"}",
     "legendFormat": "Committed  {{pod}}"
    }
   ]
  },
  {
   "title": "G1 Old Gen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{service=\"$service\",pod=~\"$pod\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{service=\"$service\", pool=\"G1 Old Gen\",pod=~\"$pod\"}",
     "legendFormat": "Used  {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{service=\"$service\", pool=\"G1 Old Gen\",pod=~\"$pod\"}",
     "legendFormat": "Committed  {{pod}}"
    }
   ]
  },
  {
   "title": "G1 Survivor Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{service=\"$service\", pool=\"G1 Survivor Space\",pod=~\"$pod\"}",
     "legendFormat": "Max  {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{service=\"$service\", pool=\"G1 Survivor Space\",pod=~\"$pod\"}",
     "legendFormat": "Used  {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{service=\"$service\", pool=\"G1 Survivor Space\",pod=~\"$pod\"}",
     "legendFormat": "Committed  {{pod}}"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{service=\"$service\", pool=\"Metaspace\",pod=~\"$pod\"}",
     "legendFormat": "Max {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{service=\"$service\", pool=\"Metaspace\",pod=~\"$pod\"}",
     "legendFormat": "Used {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{service=\"$service\", pool=\"Metaspace\",pod=~\"$pod\"}",
     "legendFormat": "Committed {{pod}}"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{service=\"$service\", pool=\"Compressed Class Space\",pod=~\"$pod\"}",
     "legendFormat": "Max {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{service=\"$service\", pool=\"Compressed Class Space\",pod=~\"$pod\"}",
     "legendFormat": "Used {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{service=\"$service\", pool=\"Compressed Class Space\",pod=~\"$pod\"}",
     "legendFormat": "Committed {{pod}}"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{service=\"$service\", pool=\"Code Cache\",pod=~\"$pod\"}",
     "legendFormat": "Max {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{service=\"$service\", pool=\"Code Cache\",pod=~\"$pod\"}",
     "legendFormat": "Used {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{service=\"$service\", pool=\"Code Cache\",pod=~\"$pod\"}",
     "legendFormat": "Committed {{pod}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "JVM current threads  {{pod}}"
    },
    {
     "expr": "jvm_threads_daemon{service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "JVM daemon threads {{pod}}"
    },
    {
     "expr": "jvm_threads_deadlocked{service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "JVM deadlocked threads  {{pod}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "{{gc}}  {{pod}}"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{service=~\"$service\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{gc}} {{pod}}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "loaded  {{pod}}"
    }
   ]
  }
 ]
}