{
  "openapi": "3.0.3",
  "info": {
    "version": "0.0.1",
    "title": "eCommerce pagoPA - NPG SDK integrity for checkout",
    "description": "Exposes the NPG SDK subresource integrity hash (source of truth), proxied from the payment-methods-handler. Consumed by the checkout NPG SDK sync pipeline to validate the SDK downloaded from NPG before publishing it to the CDN storage.",
    "contact": {
      "name": "pagoPA - Touchpoints team"
    }
  },
  "tags": [
    {
      "name": "npg-sdk-integrity",
      "description": "NPG SDK subresource integrity"
    }
  ],
  "servers": [
    {
      "url": "https://${hostname}"
    }
  ],
  "paths": {
    "/integrity": {
      "get": {
        "tags": [
          "npg-sdk-integrity"
        ],
        "summary": "Get NPG SDK integrity hash",
        "description": "Returns the SHA-384 integrity hash for the NPG SDK script, used for Subresource Integrity (SRI) checks",
        "operationId": "getNpgSdkIntegrity",
        "responses": {
          "200": {
            "description": "NPG SDK integrity hash",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NpgSdkIntegrityResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemJson"
                },
                "example": {
                  "type": "https://example.com/problem/",
                  "title": "string",
                  "status": 401,
                  "detail": "Unauthorized"
                }
              }
            }
          },
          "500": {
            "description": "Error retrieving integrity hash",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemJson"
                },
                "example": {
                  "type": "https://example.com/problem/",
                  "title": "string",
                  "status": 500,
                  "detail": "Internal server error"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "NpgSdkIntegrityResponse": {
        "type": "object",
        "required": [
          "integrityHash"
        ],
        "properties": {
          "integrityHash": {
            "type": "string",
            "description": "SHA-384 integrity hash for NPG SDK"
          }
        }
      },
      "ProblemJson": {
        "description": "Body definition for error responses containing failure details",
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "format": "uri",
            "description": "An absolute URI that identifies the problem type. When dereferenced,\nit SHOULD provide human-readable documentation for the problem type\n(e.g., using HTML).",
            "default": "about:blank",
            "example": "https://example.com/problem/constraint-violation"
          },
          "title": {
            "type": "string",
            "description": "A short, summary of the problem type. Written in english and readable\nfor engineers (usually not suited for non technical stakeholders and\nnot localized); example: Service Unavailable"
          },
          "status": {
            "$ref": "#/components/schemas/HttpStatusCode"
          },
          "detail": {
            "type": "string",
            "description": "A human readable explanation specific to this occurrence of the\nproblem.",
            "example": "There was an error processing the request"
          },
          "instance": {
            "type": "string",
            "format": "uri",
            "description": "An absolute URI that identifies the specific occurrence of the problem.\nIt may or may not yield further information if dereferenced."
          }
        }
      },
      "HttpStatusCode": {
        "type": "integer",
        "format": "int32",
        "description": "The HTTP status code generated by the origin server for this occurrence\nof the problem.",
        "minimum": 100,
        "maximum": 600,
        "exclusiveMaximum": true,
        "example": 502
      }
    }
  }
}
