#!/bin/sh

. ../dev.env

init () {
    PG_USER=$1
    PG_DB=$2
    USERNAME=$3
    PASSWORD=$4
    SCHEMA=$5
    TABLESPACE_DATA=$6
    TABLESPACE_LOB=$7
    TABLESPACE_IDX=$8

    mkdir -p /var/lib/postgresql/tablespaces/$TABLESPACE_DATA
    mkdir -p /var/lib/postgresql/tablespaces/$TABLESPACE_LOB
    mkdir -p /var/lib/postgresql/tablespaces/$TABLESPACE_IDX

    echo ""
    echo "Creating '$SCHEMA' ..."

    set -e

    echo "POSTGRES_DB_HOST ($POSTGRES_DB_HOST)"
    PGPASSWORD="$POSTGRES_PASSWORD" psql -h "$POSTGRES_DB_HOST" -p "$POSTGRES_DB_PORT" -v ON_ERROR_STOP=1 --username "$PG_USER" --dbname "$PG_DB" <<-EOSQL
    CREATE USER $USERNAME WITH PASSWORD '$PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $PG_DB TO $USERNAME;

    CREATE SCHEMA $SCHEMA AUTHORIZATION $USERNAME;

    CREATE TABLESPACE $TABLESPACE_DATA OWNER $USERNAME LOCATION '/var/lib/postgresql/tablespaces/$TABLESPACE_DATA';
    CREATE TABLESPACE $TABLESPACE_LOB OWNER $USERNAME LOCATION '/var/lib/postgresql/tablespaces/$TABLESPACE_LOB';
    CREATE TABLESPACE $TABLESPACE_IDX OWNER $USERNAME LOCATION '/var/lib/postgresql/tablespaces/$TABLESPACE_IDX';
EOSQL

    echo "Created '$SCHEMA'."
}

init $POSTGRES_USER $POSTGRES_DB \
    $NODO_CFG_USERNAME \
    $NODO_CFG_PASSWORD \
    $NODO_CFG_SCHEMA \
    $NODO_CFG_TABLESPACE_DATA \
    $NODO_CFG_TABLESPACE_LOB \
    $NODO_CFG_TABLESPACE_IDX

init $POSTGRES_USER $POSTGRES_DB \
    $NODO_ONLINE_USERNAME \
    $NODO_ONLINE_PASSWORD \
    $NODO_ONLINE_SCHEMA \
    $NODO_ONLINE_TABLESPACE_DATA \
    $NODO_ONLINE_TABLESPACE_LOB \
    $NODO_ONLINE_TABLESPACE_IDX

echo "Creating function trunc on '$NODO_ONLINE_SCHEMA' ..."
PGPASSWORD="$POSTGRES_PASSWORD" psql -h "$POSTGRES_DB_HOST" -p "$POSTGRES_DB_PORT" -v ON_ERROR_STOP=1 --username "$NODO_ONLINE_USERNAME" --dbname "$PG_DB" <<-EOSQL
    CREATE or REPLACE FUNCTION trunc(timestamp without time zone) RETURNS date
        AS 'select DATE_TRUNC(''day'',\$1);'
        LANGUAGE SQL
        IMMUTABLE
        RETURNS NULL ON NULL INPUT;
EOSQL
echo "Created function trunc on '$NODO_ONLINE_SCHEMA'"

init $POSTGRES_USER $POSTGRES_DB \
    $NODO_OFFLINE_USERNAME \
    $NODO_OFFLINE_PASSWORD \
    $NODO_OFFLINE_SCHEMA \
    $NODO_OFFLINE_TABLESPACE_DATA \
    $NODO_OFFLINE_TABLESPACE_LOB \
    $NODO_OFFLINE_TABLESPACE_IDX

init $POSTGRES_USER $POSTGRES_DB \
    $NODO_WFESP_USERNAME \
    $NODO_WFESP_PASSWORD \
    $NODO_WFESP_SCHEMA \
    $NODO_WFESP_TABLESPACE_DATA \
    $NODO_WFESP_TABLESPACE_LOB \
    $NODO_WFESP_TABLESPACE_IDX

init $POSTGRES_USER $POSTGRES_DB \
    $NODO_RE_USERNAME \
    $NODO_RE_PASSWORD \
    $NODO_RE_SCHEMA \
    $NODO_RE_TABLESPACE_DATA \
    $NODO_RE_TABLESPACE_LOB \
    $NODO_RE_TABLESPACE_IDX
