{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "Notification API",
    "description": "API to support notifications"
  },
  "host": "${hostname}",
  "basePath": "/notifications",
  "schemes": [
    "https"
  ],
  "paths": {
    "/emails": {
      "x-swagger-router-controller": "emailController",
      "post": {
        "operationId": "sendNotificationEmail",
        "summary": "New Notification email",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "schema": {
              "$ref": "#/definitions/NotificationEmailRequest"
            },
            "required": true
          },
          {
            "in": "header",
            "name": "ocp-apim-subscription-key",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Email notification started",
            "schema": {
              "$ref": "#/definitions/NotificationEmailResponse"
            },
            "examples": {
              "application/json": {
                "importoSingoloVersamento": 200
              }
            }
          },
          "400": {
            "description": "Invalid input",
            "schema": {
              "$ref": "#/definitions/ProblemJson"
            }
          },
          "500": {
            "description": "Generic server error",
            "schema": {
              "$ref": "#/definitions/ProblemJson"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "NotificationEmailRequest": {
      "type": "object",
      "properties": {
        "to": {
          "type": "string",
          "format": "email"
        },
        "subject": {
          "type": "string"
        },
        "templateId": {
          "type": "string"
        },
        "parameters": {
          "type": "object",
          "additionalProperties": true
        },
        "language": {
          "type": "string",
          "format": "iso639-1"
        }
      },
      "required": [
        "to",
        "subject",
        "templateId",
        "parameters"
      ]
    },
    "NotificationEmailResponse": {
      "type": "object",
      "properties": {
        "outcome": {
          "type": "string"
        }
      }
    },
    "HttpStatusCode": {
      "type": "integer",
      "format": "int32",
      "description": "The HTTP status code generated by the origin server for this occurrence\nof the problem.",
      "minimum": 100,
      "maximum": 600,
      "exclusiveMaximum": true,
      "example": 200
    },
    "ProblemJson": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "format": "uri",
          "description": "An absolute URI that identifies the problem type. When dereferenced,\nit SHOULD provide human-readable documentation for the problem type\n(e.g., using HTML).",
          "default": "about:blank",
          "example": "https://example.com/problem/constraint-violation"
        },
        "title": {
          "type": "string",
          "description": "A short, summary of the problem type. Written in english and readable\nfor engineers (usually not suited for non technical stakeholders and\nnot localized); example: Service Unavailable"
        },
        "status": {
          "$ref": "#/definitions/HttpStatusCode"
        },
        "detail": {
          "type": "string",
          "description": "A human readable explanation specific to this occurrence of the\nproblem.",
          "example": "There was an error processing the request"
        },
        "instance": {
          "type": "string",
          "format": "uri",
          "description": "An absolute URI that identifies the specific occurrence of the problem.\nIt may or may not yield further information if dereferenced."
        }
      }
    }
  }
}