insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('carrello','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('cd_info_pagamento','online','OBJ_ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('idempotency_cache','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('messaggi','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('pm_metadata','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('pm_session_data','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('position_activate','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('position_payment','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('position_payment_plan','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('position_payment_status','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('position_payment_status_snapshot','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('position_receipt','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('position_receipt_recipient','online',NULL);
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('position_receipt_recipient_status','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('position_receipt_transfer','online',NULL);
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('position_receipt_xml','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('position_retry_pa_send_rt','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('position_retry_sendpaymentresult','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('position_service','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('position_status','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('position_status_snapshot','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('position_subject','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('position_transfer','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('retry_pa_attiva_rpt','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('retry_pa_invia_rt','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('retry_rpt','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('rpt','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('rpt_activations','online',NULL);
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('rpt_soggetti','online','RPT_ID, TIPO_SOGGETTO');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('rpt_versamenti','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('rpt_versamenti_bollo','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('rpt_xml','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('rt','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('rt_versamenti','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('rt_versamenti_bollo','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('rt_xml','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('stati_carrello','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('stati_carrello_snapshot','online','ID_CARRELLO');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('stati_rpt','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('stati_rpt_snapshot','online','ID_DOMINIO, IUV, CCP');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('token_utility','online','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('verifica_bollettino','online','ID');

insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('rendicontazione_sftp_receive_queue','offline','ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('rendicontazione_sftp_send_queue','offline','ID');

insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('re','re','ID');

insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('carrello_rpt','wfesp','OBJ_ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('redirect_my_bank','wfesp','OBJ_ID');
insert into ${schema}.tab_part(tabella,schema,campi_indice)values ('rpt','wfesp','OBJ_ID');
