{
    "openapi": "3.0.0",
    "info": {
        "version": "1.0.0",
        "title": "Pagopa Feature Flags",
        "description": "This API set contains APIM level APIs used to manage feature flags for checkout."
    },
    "servers": [
        {
            "url": "https://${host}"
        }
    ],
    "tags": [
        {
            "name": "featureFlags",
            "description": "This API is used to handle feature flags for checkout, and follows the Openfeature specifications.",
            "externalDocs": {
                "url": "https://openfeature.dev",
                "description": "Openfeature"
            }
        }
    ],
    "paths": {
        "/features/values": {
            "get": {
                "operationId": "evaluateFeatureFlags",
                "tags": ["featureFlags"],
                "summary": Evaluate feature flags values",
                "description": "Returns the values of all feature flags.",
                "responses": {
                    "200": {
                        "description": "Feature flags values",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/FeatureFlagsResponse"
                                },
                                "example": {
                                    "featureName_1": "value_1",
                                    "featureName_2": "value_2",
                                    "featureName_3": "value_3"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ProblemJson"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "FeatureFlagsResponse": {
                "type": "object",
                "additionalProperties": true,
                "description": "A JSON object containing feature names and their values."
            },
            "ProblemJson": {
                "type": "object",
                "properties": {
                    "type": {
                        "type": "string",
                        "format": "uri",
                        "description": "An absolute URI that identifies the problem type. When dereferenced, it SHOULD provide human-readable documentation for the problem type (e.g., using HTML).",
                        "default": "about:blank",
                        "example": "https://example.com/problem/constraint-violation"
                    },
                    "title": {
                        "type": "string",
                        "description": "A short, summary of the problem type. Written in English and readable for engineers (usually not suited for non-technical stakeholders and not localized); example: Service Unavailable"
                    },
                    "status": {
                        "$ref": "#/components/schemas/HttpStatusCode"
                    },
                    "detail": {
                        "type": "string",
                        "description": "A human-readable explanation specific to this occurrence of the problem.",
                        "example": "There was an error processing the request"
                    },
                    "instance": {
                        "type": "string",
                        "format": "uri",
                        "description": "An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced."
                    }
                }
            },
            "HttpStatusCode": {
                "type": "integer",
                "format": "int32",
                "description": "The HTTP status code generated by the origin server for this occurrence of the problem.",
                "minimum": 100,
                "maximum": 600,
                "exclusiveMaximum": true,
                "example": 200
            }
        }
    }
}
