apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: ${namespace}
spec:
  mode: deployment # This configuration is omittable.
  config: |
    receivers:
      otlp:
        protocols:
          grpc:

    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 2000
      batch:
      resource:
        attributes:
        - key: deployment.environment
          value: ${deployment_env}
          action: upsert

    exporters:
      logging:
        loglevel: warn

      otlphttp/elastic:
        tls:
          insecure: true
        endpoint: "${apm_endpoint}"
        headers:
          Authorization: "${apm_authorization}"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [resource]
          exporters: [logging, otlphttp/elastic]
        metrics:
          receivers: [otlp]
          processors: [resource]
          exporters: [logging, otlphttp/elastic]
        logs:
          receivers: [otlp]
          processors: [resource]
          exporters: [logging, otlphttp/elastic]
