CREATE UNIQUE INDEX "${schema}"."NODO_ONLINE_RPT_IDX1" ON "${schema}"."RPT" ("PARAMETRI_PAGAMENTO_IMMEDIATO", "PSP", "CODICE_CARRELLO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

  ALTER INDEX "${schema}"."NODO_ONLINE_RPT_IDX1" NOPARALLEL;
-- new object type path: SCHEMA_EXPORT/TABLE/CONSTRAINT/CONSTRAINT
-- CONNECT SYS
ALTER TABLE "${schema}"."CARRELLO_RPT" ADD CONSTRAINT "CARRELLO_RPT_PK" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."CARRELLO_RPT_PK" ON "${schema}"."CARRELLO_RPT" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  )  ENABLE;
ALTER TABLE "${schema}"."CARRELLO_RPT" ADD CONSTRAINT "NODO_ONLINE_CARRELLO_IDX1_UNI" UNIQUE ("PARAMETRI_PAGAMENTO_IMMEDIATO", "PSP", "CODICE_CARRELLO")
  USING INDEX "${schema}"."NODO_ONLINE_CARRELLO_IDX1"  ENABLE;
ALTER TABLE "${schema}"."REDIRECT_MY_BANK" ADD CONSTRAINT "REDIRECT_MY_BANK_PK" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."REDIRECT_MY_BANK_PK" ON "${schema}"."REDIRECT_MY_BANK" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  )  ENABLE;
ALTER TABLE "${schema}"."RPT" ADD CONSTRAINT "NODO_ONLINE_RPT_IDX1_UNI" UNIQUE ("PARAMETRI_PAGAMENTO_IMMEDIATO", "PSP", "CODICE_CARRELLO")
  USING INDEX "${schema}"."NODO_ONLINE_RPT_IDX1"  ENABLE;
ALTER TABLE "${schema}"."RPT" ADD CONSTRAINT "RPT_PK" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."RPT_PK" ON "${schema}"."RPT" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  )  ENABLE;
-- new object type path: SCHEMA_EXPORT/TABLE/CONSTRAINT/REF_CONSTRAINT
ALTER TABLE "${schema}"."REDIRECT_MY_BANK" ADD CONSTRAINT "REDIRECT_MYBANK_FK_RPT" FOREIGN KEY ("REDIRECT_RPT")
	  REFERENCES "${schema}"."RPT" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."REDIRECT_MY_BANK" ADD CONSTRAINT "REDIRECT_MY_BANK_FK_CARRELLO_RPT" FOREIGN KEY ("REDIRECT_CARRELLO")
	  REFERENCES "${schema}"."CARRELLO_RPT" ("OBJ_ID") ENABLE;
