CREATE TABLE "${schema}"."RPT"
   (	"OBJ_ID" NUMBER DEFAULT "${schema}"."RPT_SEQ".NEXTVAL,
	"ID_DOMINIO" VARCHAR2(35 CHAR) NOT NULL ENABLE,
	"IUV" VARCHAR2(35 CHAR) NOT NULL ENABLE,
	"CCP" VARCHAR2(35 CHAR) NOT NULL ENABLE,
	"CODICE_CARRELLO" VARCHAR2(128 CHAR),
	"STAZ_INTERMEDIARIOPA" VARCHAR2(35 CHAR),
	"INTERMEDIARIOPA" VARCHAR2(35 CHAR),
	"CANALE" VARCHAR2(35 CHAR),
	"INTERMEDIARIOPSP" VARCHAR2(35 CHAR),
	"PSP" VARCHAR2(35 CHAR),
	"ID_SESSIONE" VARCHAR2(100 CHAR) NOT NULL ENABLE,
	"PARAMETRI_PAGAMENTO_IMMEDIATO" VARCHAR2(255 CHAR),
	"PARAMETRI_PROFILO_PAGAMENTO" VARCHAR2(255 CHAR),
	"URL_REDIREZIONE_PA" VARCHAR2(255 CHAR),
	"URL_REDIREZIONE_PSP" VARCHAR2(255 CHAR),
	"STATO" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"RETURN_CODE" VARCHAR2(10 CHAR),
	"ESITO_REDIRECT" VARCHAR2(50 CHAR),
	"TIPO_INTERAZIONE" VARCHAR2(255 CHAR),
	"MOBILE_TOKEN" VARCHAR2(255 CHAR),
	"RRN" VARCHAR2(255 CHAR),
	"ESITO_TRANSAZIONE_CARTA" VARCHAR2(35 CHAR),
	"CODICE_AUTORIZZATIVO" VARCHAR2(6 CHAR),
	"PARAMETRI_PM" VARCHAR2(255 CHAR),
	"TIMESTAMP_OPERAZIONE" TIMESTAMP (6),
	"IMPORTO_TOTALE_PAGATO" NUMBER(19,0),
	"INSERTED_TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE,
	"INSERTED_BY" VARCHAR2(35 CHAR) DEFAULT 'INSERTED_BY' NOT NULL ENABLE,
	"UPDATED_TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE,
	"UPDATED_BY" VARCHAR2(35 CHAR) DEFAULT 'UPDATED_BY' NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS  LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  PARTITION BY RANGE ("INSERTED_TIMESTAMP") INTERVAL (NUMTODSINTERVAL (1, 'DAY'))
 (PARTITION "SYS_P71497"  VALUES LESS THAN (TIMESTAMP' 2019-04-01 00:00:00') SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  READ WRITE) ;
CREATE TABLE "${schema}"."CARRELLO_RPT"
   (	"OBJ_ID" NUMBER DEFAULT "${schema}"."CARRELLO_RPT_SEQ".NEXTVAL,
	"ID_CARRELLO" VARCHAR2(35 CHAR),
	"CODICE_CARRELLO" VARCHAR2(128 CHAR),
	"STAZ_INTERMEDIARIOPA" VARCHAR2(35 CHAR),
	"INTERMEDIARIOPA" VARCHAR2(35 CHAR),
	"CANALE" VARCHAR2(35 CHAR),
	"INTERMEDIARIOPSP" VARCHAR2(35 CHAR),
	"PSP" VARCHAR2(35 CHAR),
	"ID_SESSIONE" VARCHAR2(100 CHAR) NOT NULL ENABLE,
	"PARAMETRI_PAGAMENTO_IMMEDIATO" VARCHAR2(255 CHAR),
	"PARAMETRI_PROFILO_PAGAMENTO" VARCHAR2(255 CHAR),
	"URL_REDIREZIONE_PA" VARCHAR2(255 CHAR),
	"URL_REDIREZIONE_PSP" VARCHAR2(255 CHAR),
	"STATO" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"RETURN_CODE" VARCHAR2(10 CHAR),
	"ESITO_REDIRECT" VARCHAR2(50 CHAR),
	"TIPO_INTERAZIONE" VARCHAR2(255 CHAR),
	"MOBILE_TOKEN" VARCHAR2(255 CHAR),
	"RRN" VARCHAR2(255 CHAR),
	"ESITO_TRANSAZIONE_CARTA" VARCHAR2(35 CHAR),
	"CODICE_AUTORIZZATIVO" VARCHAR2(6 CHAR),
	"PARAMETRI_PM" VARCHAR2(255 CHAR),
	"TIMESTAMP_OPERAZIONE" TIMESTAMP (6),
	"IMPORTO_TOTALE_PAGATO" NUMBER(19,0),
	"INSERTED_TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE,
	"INSERTED_BY" VARCHAR2(35 CHAR) DEFAULT 'INSERTED_BY' NOT NULL ENABLE,
	"UPDATED_TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE,
	"UPDATED_BY" VARCHAR2(35 CHAR) DEFAULT 'UPDATED_BY' NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS  LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  PARTITION BY RANGE ("INSERTED_TIMESTAMP") INTERVAL (NUMTODSINTERVAL (1, 'DAY'))
 (PARTITION "SYS_P71498"  VALUES LESS THAN (TIMESTAMP' 2019-04-01 00:00:00') SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  READ WRITE ) ;
CREATE TABLE "${schema}"."REDIRECT_MY_BANK"
   (	"OBJ_ID" NUMBER DEFAULT "${schema}"."REDIRECT_MY_BANK_SEQ".NEXTVAL,
	"ID_DOMINIO" VARCHAR2(35 CHAR),
	"IUV" VARCHAR2(35 CHAR),
	"CCP" VARCHAR2(35 CHAR),
	"NUMERO_ORDINE" VARCHAR2(50 CHAR),
	"DESCR_ORDINE" VARCHAR2(140 CHAR),
	"CODICE_MYBANK" VARCHAR2(35 CHAR),
	"ID_NEGOZIO" VARCHAR2(15 CHAR),
	"IMPORTO" NUMBER(10,0),
	"CHIAVE_AVVIO" VARCHAR2(255 CHAR),
	"CHIAVE_ESITO" VARCHAR2(255 CHAR),
	"MAC_RICHIESTA" VARCHAR2(100 CHAR),
	"MAC_ESITO" VARCHAR2(100 CHAR),
	"ESITO_MS" VARCHAR2(255 CHAR),
	"AUT" VARCHAR2(35 CHAR),
	"BPW_TIPO_TRANSAZIONE" VARCHAR2(255 CHAR),
	"ID_TRANS" VARCHAR2(25 CHAR),
	"STATO_SITORD" VARCHAR2(255 CHAR),
	"ESITO_SITORD" VARCHAR2(255 CHAR),
	"REQREFNUM" VARCHAR2(32 CHAR),
	"STATO_PAGAMENTO" VARCHAR2(100 CHAR),
	"URL_SITUAZIONE_ORDINE" VARCHAR2(255 CHAR),
	"REDIRECT_RPT" NUMBER,
	"REDIRECT_CARRELLO" NUMBER,
	"TIMESTAMP_ESITO" TIMESTAMP (6),
	"INSERTED_TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE,
	"INSERTED_BY" VARCHAR2(35 CHAR) NOT NULL ENABLE,
	"UPDATED_TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE,
	"UPDATED_BY" VARCHAR2(35 CHAR) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS  LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  PARTITION BY RANGE ("INSERTED_TIMESTAMP") INTERVAL (NUMTODSINTERVAL (1, 'DAY'))
 (PARTITION "SYS_P71499"  VALUES LESS THAN (TIMESTAMP' 2019-04-01 00:00:00') SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  READ WRITE) ;