{
  "openapi": "3.0.0",
  "info": {
    "title": "Notification API",
    "description": "API to support notifications",
    "version": "0.0.1",
    "contact": {
      "name": "pagoPA - Touchpoints team"
    }
  },
  "externalDocs": {
    "url": "https://pagopa.atlassian.net/wiki/spaces/I/pages/611745800/-servizio+notifications+service",
    "description": "Technical specifications"
  },
  "servers": [
    {
      "url": "https://${hostname}/notifications"
    }
  ],
  "security": [
    {
      "ApiKeyAuth": []
    }
  ],
  "paths": {
    "/emails": {
      "post": {
        "summary": "New Notification email",
        "description": "Api used to process a new email notification",
        "operationId": "sendNotificationEmail",
        "parameters": [
          {
            "name": "ocp-apim-subscription-key",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/NotificationEmailRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Email notification started",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NotificationEmailResponse"
                }
              }
            }
          },
          "202": {
            "description": "Email notification enqueued",
            "content": {}
          },
          "400": {
            "description": "Invalid input",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemJson"
                }
              }
            }
          },
          "500": {
            "description": "Generic server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemJson"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "NotificationEmailRequest": {
        "type": "object",
        "description": "Request body containing info about the mail to be sent",
        "properties": {
          "to": {
            "description": "Email recipient",
            "type": "string",
            "format": "email"
          },
          "subject": {
            "description": "Email subject",
            "type": "string"
          },
          "templateId": {
            "description": "Email template unique identifier",
            "type": "string"
          },
          "parameters": {
            "description": "Parameters used to value email templates",
            "type": "object",
            "properties": {}
          },
          "language": {
            "description": "Language",
            "type": "string",
            "format": "iso639-1"
          }
        },
        "required": [
          "parameters",
          "subject",
          "templateId",
          "to"
        ]
      },
      "NotificationEmailResponse": {
        "description": "New mail response body",
        "type": "object",
        "properties": {
          "outcome": {
            "description": "Email notification outcome",
            "type": "string"
          }
        }
      },
      "HttpStatusCode": {
        "maximum": 600,
        "exclusiveMaximum": true,
        "minimum": 100,
        "type": "integer",
        "description": "The HTTP status code generated by the origin server for this occurrence\nof the problem.",
        "format": "int32",
        "example": 200
      },
      "ProblemJson": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "description": "An absolute URI that identifies the problem type. When dereferenced,\nit SHOULD provide human-readable documentation for the problem type\n(e.g., using HTML).",
            "format": "uri",
            "example": "https://example.com/problem/constraint-violation",
            "default": "about:blank"
          },
          "title": {
            "type": "string",
            "description": "A short, summary of the problem type. Written in english and readable\nfor engineers (usually not suited for non technical stakeholders and\nnot localized); example: Service Unavailable"
          },
          "status": {
            "$ref": "#/components/schemas/HttpStatusCode"
          },
          "detail": {
            "type": "string",
            "description": "A human readable explanation specific to this occurrence of the\nproblem.",
            "example": "There was an error processing the request"
          },
          "instance": {
            "type": "string",
            "description": "An absolute URI that identifies the specific occurrence of the problem.\nIt may or may not yield further information if dereferenced.",
            "format": "uri"
          }
        }
      }
    },
    "securitySchemes": {
      "ApiKeyAuth": {
        "type": "apiKey",
        "name": "Ocp-Apim-Subscription-Key",
        "in": "header"
      }
    }
  }
}