{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "Pagopa api used to handle NPG SDK resources",
    "description": "Api used to retrieve and validate (sub resource integrity) NPG SDK"
  },
  "servers": [
    {
      "url": "https://${host}"
    }
  ],
  "tags": [
    {
      "name": "npgSDK",
      "description": "NPG SDK api's",
      "externalDocs": {
        "url": "https://TODO",
        "description": "Technical specifications"
      }
    }
  ],
  "paths": {
    "/npg/resources/sdk": {
      "get": {
        "tags": [
          "npgSDK"
        ],
        "operationId": "getSdk",
        "summary": "Retrieve NPG SDK",
        "description": "GET NPG SDK resource",
        "responses": {
          "200": {
            "description": "SDK resource returned successfully"
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemJson"
                }
              }
            }
          }
        }
      }
    },
    "/npg/resources/sdk/sri": {
      "get": {
        "tags": [
          "npgSDK"
        ],
        "operationId": "getSdkSriInfo",
        "summary": "Retrieve NPG SDK S(ub)R(esource)I(ntegrity) informations",
        "description": "GET NPG SDK resource",
        "responses": {
          "200": {
            "description": "NPG SDK SRI informations",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SriResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error retrieving SRI informations",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemJson"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "SriResponse": {
        "type": "object",
        "properties": {
          "integrityHash": {
            "type": "string",
            "description": "SDK instance hash value"
          }
        },
        "required": [
          "integrityHash"
        ]
      },
      "ProblemJson": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "format": "uri",
            "description": "An absolute URI that identifies the problem type. When dereferenced,\nit SHOULD provide human-readable documentation for the problem type\n(e.g., using HTML).",
            "default": "about:blank",
            "example": "https://example.com/problem/constraint-violation"
          },
          "title": {
            "type": "string",
            "description": "A short, summary of the problem type. Written in english and readable\nfor engineers (usually not suited for non technical stakeholders and\nnot localized); example: Service Unavailable"
          },
          "status": {
            "$ref": "#/components/schemas/HttpStatusCode"
          },
          "detail": {
            "type": "string",
            "description": "A human readable explanation specific to this occurrence of the\nproblem.",
            "example": "There was an error processing the request"
          },
          "instance": {
            "type": "string",
            "format": "uri",
            "description": "An absolute URI that identifies the specific occurrence of the problem.\nIt may or may not yield further information if dereferenced."
          }
        }
      },
      "HttpStatusCode": {
        "type": "integer",
        "format": "int32",
        "description": "The HTTP status code generated by the origin server for this occurrence\nof the problem.",
        "minimum": 100,
        "maximum": 600,
        "exclusiveMaximum": true,
        "example": 200
      }
    }
  }
}