{
 "title": "Nodo Opex - Nodo per eCommerce V2",
 "tags": [
  "ndp",
  "nodo",
  "nodo dei pagamenti",
  "generated"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "No filter,Nexi Oracle,Nexi Postgres,PagoPA Postgres"
   }
  ]
 },
 "panels": [
  {
   "title": "closePaymentV2 Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"closePaymentV2\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize total = count(), ko = countif(outcome != \"OK\") by bin(timestamp, 1m)\n| extend availability = 1 - todouble(ko) / todouble(total)\n| project timestamp, value = availability, series = \"Availability\"\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "closePaymentV2 Fault Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"closePaymentV2\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize count() by bin(timestamp, 1m), outcome\n| project timestamp, value = count_, series = outcome\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "closePaymentV2 Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"closePaymentV2\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=avg(duration) by bin(timestamp, 5m)\n| project timestamp, value, series = \"Avg\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    },
    {
     "azureLogAnalytics": {
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"closePaymentV2\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=percentile(duration, 95) by bin(timestamp, 5m)\n| project timestamp, value, series = \"P95\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  }
 ]
}