{
 "title": "Nodo Opex - Nodo per PA Auth",
 "tags": [
  "ndp",
  "nodo",
  "nodo dei pagamenti",
  "generated"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "No filter,Nexi Oracle,Nexi Postgres,PagoPA Postgres"
   }
  ]
 },
 "panels": [
  {
   "title": "nodoChiediElencoFlussiRendicontazione Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63b6e2da2a92e811a8f338f8\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize total = count(), ko = countif(outcome != \"OK\") by bin(timestamp, 1m)\n| extend availability = 1 - todouble(ko) / todouble(total)\n| project timestamp, value = availability, series = \"Availability\"\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoChiediElencoFlussiRendicontazione Fault Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63b6e2da2a92e811a8f338f8\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize count() by bin(timestamp, 1m), outcome\n| project timestamp, value = count_, series = outcome\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoChiediElencoFlussiRendicontazione Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63b6e2da2a92e811a8f338f8\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=avg(duration) by bin(timestamp, 1m)\n| project timestamp, value, series = \"Avg\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    },
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63b6e2da2a92e811a8f338f8\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=percentile(duration, 95) by bin(timestamp, 1m)\n| project timestamp, value, series = \"P95\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoChiediElencoQuadraturePA Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63e5d8212a92e80448d38e04\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize total = count(), ko = countif(outcome != \"OK\") by bin(timestamp, 1m)\n| extend availability = 1 - todouble(ko) / todouble(total)\n| project timestamp, value = availability, series = \"Availability\"\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoChiediElencoQuadraturePA Fault Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63e5d8212a92e80448d38e04\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize count() by bin(timestamp, 1m), outcome\n| project timestamp, value = count_, series = outcome\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoChiediElencoQuadraturePA Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63e5d8212a92e80448d38e04\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=avg(duration) by bin(timestamp, 1m)\n| project timestamp, value, series = \"Avg\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    },
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63e5d8212a92e80448d38e04\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=percentile(duration, 95) by bin(timestamp, 1m)\n| project timestamp, value, series = \"P95\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoChiediFlussoRendicontazione Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63b6e2da2a92e811a8f338f9\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize total = count(), ko = countif(outcome != \"OK\") by bin(timestamp, 1m)\n| extend availability = 1 - todouble(ko) / todouble(total)\n| project timestamp, value = availability, series = \"Availability\"\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoChiediFlussoRendicontazione Fault Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63b6e2da2a92e811a8f338f9\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize count() by bin(timestamp, 1m), outcome\n| project timestamp, value = count_, series = outcome\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoChiediFlussoRendicontazione Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63b6e2da2a92e811a8f338f9\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=avg(duration) by bin(timestamp, 1m)\n| project timestamp, value, series = \"Avg\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    },
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63b6e2da2a92e811a8f338f9\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=percentile(duration, 95) by bin(timestamp, 1m)\n| project timestamp, value, series = \"P95\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoChiediInformativaPSP Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63e5d8212a92e80448d38e02\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize total = count(), ko = countif(outcome != \"OK\") by bin(timestamp, 1m)\n| extend availability = 1 - todouble(ko) / todouble(total)\n| project timestamp, value = availability, series = \"Availability\"\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoChiediInformativaPSP Fault Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63e5d8212a92e80448d38e02\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize count() by bin(timestamp, 1m), outcome\n| project timestamp, value = count_, series = outcome\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoChiediInformativaPSP Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63e5d8212a92e80448d38e02\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=avg(duration) by bin(timestamp, 1m)\n| project timestamp, value, series = \"Avg\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    },
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63e5d8212a92e80448d38e02\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=percentile(duration, 95) by bin(timestamp, 1m)\n| project timestamp, value, series = \"P95\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoChiediListaPendentiRPT Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63e5d8212a92e80448d38dfe\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize total = count(), ko = countif(outcome != \"OK\") by bin(timestamp, 1m)\n| extend availability = 1 - todouble(ko) / todouble(total)\n| project timestamp, value = availability, series = \"Availability\"\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoChiediListaPendentiRPT Fault Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63e5d8212a92e80448d38dfe\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize count() by bin(timestamp, 1m), outcome\n| project timestamp, value = count_, series = outcome\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoChiediListaPendentiRPT Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63e5d8212a92e80448d38dfe\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=avg(duration) by bin(timestamp, 1m)\n| project timestamp, value, series = \"Avg\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    },
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63e5d8212a92e80448d38dfe\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=percentile(duration, 95) by bin(timestamp, 1m)\n| project timestamp, value, series = \"P95\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoChiediQuadraturaPA Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63e5d8212a92e80448d38e05\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize total = count(), ko = countif(outcome != \"OK\") by bin(timestamp, 1m)\n| extend availability = 1 - todouble(ko) / todouble(total)\n| project timestamp, value = availability, series = \"Availability\"\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoChiediQuadraturaPA Fault Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63e5d8212a92e80448d38e05\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize count() by bin(timestamp, 1m), outcome\n| project timestamp, value = count_, series = outcome\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoChiediQuadraturaPA Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63e5d8212a92e80448d38e05\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=avg(duration) by bin(timestamp, 1m)\n| project timestamp, value, series = \"Avg\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    },
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63e5d8212a92e80448d38e05\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=percentile(duration, 95) by bin(timestamp, 1m)\n| project timestamp, value, series = \"P95\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoChiediStatoRPT Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63e5d8212a92e80448d38dfd\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize total = count(), ko = countif(outcome != \"OK\") by bin(timestamp, 1m)\n| extend availability = 1 - todouble(ko) / todouble(total)\n| project timestamp, value = availability, series = \"Availability\"\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoChiediStatoRPT Fault Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63e5d8212a92e80448d38dfd\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize count() by bin(timestamp, 1m), outcome\n| project timestamp, value = count_, series = outcome\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoChiediStatoRPT Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63e5d8212a92e80448d38dfd\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=avg(duration) by bin(timestamp, 1m)\n| project timestamp, value, series = \"Avg\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    },
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63e5d8212a92e80448d38dfd\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=percentile(duration, 95) by bin(timestamp, 1m)\n| project timestamp, value, series = \"P95\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoInviaCarrelloRPT Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63e5d8212a92e80448d38e00\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize total = count(), ko = countif(outcome != \"OK\") by bin(timestamp, 1m)\n| extend availability = 1 - todouble(ko) / todouble(total)\n| project timestamp, value = availability, series = \"Availability\"\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoInviaCarrelloRPT Fault Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63e5d8212a92e80448d38e00\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize count() by bin(timestamp, 1m), outcome\n| project timestamp, value = count_, series = outcome\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoInviaCarrelloRPT Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63e5d8212a92e80448d38e00\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=avg(duration) by bin(timestamp, 1m)\n| project timestamp, value, series = \"Avg\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    },
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63e5d8212a92e80448d38e00\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=percentile(duration, 95) by bin(timestamp, 1m)\n| project timestamp, value, series = \"P95\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoInviaRPT Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63e5d8212a92e80448d38dff\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize total = count(), ko = countif(outcome != \"OK\") by bin(timestamp, 1m)\n| extend availability = 1 - todouble(ko) / todouble(total)\n| project timestamp, value = availability, series = \"Availability\"\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoInviaRPT Fault Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63e5d8212a92e80448d38dff\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize count() by bin(timestamp, 1m), outcome\n| project timestamp, value = count_, series = outcome\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoInviaRPT Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63e5d8212a92e80448d38dff\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=avg(duration) by bin(timestamp, 1m)\n| project timestamp, value, series = \"Avg\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    },
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63e5d8212a92e80448d38dff\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=percentile(duration, 95) by bin(timestamp, 1m)\n| project timestamp, value, series = \"P95\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoPAChiediInformativaPA Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63e5d8212a92e80448d38e03\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize total = count(), ko = countif(outcome != \"OK\") by bin(timestamp, 1m)\n| extend availability = 1 - todouble(ko) / todouble(total)\n| project timestamp, value = availability, series = \"Availability\"\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoPAChiediInformativaPA Fault Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63e5d8212a92e80448d38e03\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize count() by bin(timestamp, 1m), outcome\n| project timestamp, value = count_, series = outcome\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoPAChiediInformativaPA Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63e5d8212a92e80448d38e03\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=avg(duration) by bin(timestamp, 1m)\n| project timestamp, value, series = \"Avg\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    },
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63e5d8212a92e80448d38e03\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=percentile(duration, 95) by bin(timestamp, 1m)\n| project timestamp, value, series = \"P95\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "[DEPRECATED] nodoChiediCopiaRT Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63e5d8212a92e80448d38e01\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize total = count(), ko = countif(outcome != \"OK\") by bin(timestamp, 1m)\n| extend availability = 1 - todouble(ko) / todouble(total)\n| project timestamp, value = availability, series = \"Availability\"\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "[DEPRECATED] nodoChiediCopiaRT Fault Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 80 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63e5d8212a92e80448d38e01\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize count() by bin(timestamp, 1m), outcome\n| project timestamp, value = count_, series = outcome\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "[DEPRECATED] nodoChiediCopiaRT Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63e5d8212a92e80448d38e01\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=avg(duration) by bin(timestamp, 1m)\n| project timestamp, value, series = \"Avg\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    },
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63e5d8212a92e80448d38e01\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it/nodo\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=percentile(duration, 95) by bin(timestamp, 1m)\n| project timestamp, value, series = \"P95\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  }
 ]
}