{
 "title": "Nodo Opex - Node for PSP",
 "tags": [
  "ndp",
  "nodo",
  "nodo dei pagamenti",
  "generated"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "No filter,Nexi Oracle,Nexi Postgres,PagoPA Postgres"
   }
  ]
 },
 "panels": [
  {
   "title": "activatePaymentNotice Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"61dedafc2a92e81a0c7a58fc\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize total = count(), ko = countif(outcome != \"OK\") by bin(timestamp, 1m)\n| extend availability = 1 - todouble(ko) / todouble(total)\n| project timestamp, value = availability, series = \"Availability\"\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "activatePaymentNotice Fault Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"61dedafc2a92e81a0c7a58fc\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize count() by bin(timestamp, 1m), outcome\n| project timestamp, value = count_, series = outcome\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "activatePaymentNotice Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"61dedafc2a92e81a0c7a58fc\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=avg(duration) by bin(timestamp, 1m)\n| project timestamp, value, series = \"Avg\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    },
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"61dedafc2a92e81a0c7a58fc\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=percentile(duration, 95) by bin(timestamp, 1m)\n| project timestamp, value, series = \"P95\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "activatePaymentNoticeV2 Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63c559672a92e811a8f33a00\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize total = count(), ko = countif(outcome != \"OK\") by bin(timestamp, 1m)\n| extend availability = 1 - todouble(ko) / todouble(total)\n| project timestamp, value = availability, series = \"Availability\"\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "activatePaymentNoticeV2 Fault Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63c559672a92e811a8f33a00\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize count() by bin(timestamp, 1m), outcome\n| project timestamp, value = count_, series = outcome\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "activatePaymentNoticeV2 Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63c559672a92e811a8f33a00\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=avg(duration) by bin(timestamp, 1m)\n| project timestamp, value, series = \"Avg\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    },
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63c559672a92e811a8f33a00\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=percentile(duration, 95) by bin(timestamp, 1m)\n| project timestamp, value, series = \"P95\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "demandPaymentNotice Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"62bb23bdea7c4a0f183fc065\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize total = count(), ko = countif(outcome != \"OK\") by bin(timestamp, 1m)\n| extend availability = 1 - todouble(ko) / todouble(total)\n| project timestamp, value = availability, series = \"Availability\"\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "demandPaymentNotice Fault Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"62bb23bdea7c4a0f183fc065\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize count() by bin(timestamp, 1m), outcome\n| project timestamp, value = count_, series = outcome\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "demandPaymentNotice Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"62bb23bdea7c4a0f183fc065\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=avg(duration) by bin(timestamp, 1m)\n| project timestamp, value, series = \"Avg\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    },
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"62bb23bdea7c4a0f183fc065\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=percentile(duration, 95) by bin(timestamp, 1m)\n| project timestamp, value, series = \"P95\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoChiediCatalogoServiziV2 Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"62bb23bdea7c4a0f183fc066\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize total = count(), ko = countif(outcome != \"OK\") by bin(timestamp, 1m)\n| extend availability = 1 - todouble(ko) / todouble(total)\n| project timestamp, value = availability, series = \"Availability\"\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoChiediCatalogoServiziV2 Fault Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"62bb23bdea7c4a0f183fc066\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize count() by bin(timestamp, 1m), outcome\n| project timestamp, value = count_, series = outcome\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "nodoChiediCatalogoServiziV2 Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"62bb23bdea7c4a0f183fc066\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=avg(duration) by bin(timestamp, 1m)\n| project timestamp, value, series = \"Avg\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    },
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"62bb23bdea7c4a0f183fc066\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=percentile(duration, 95) by bin(timestamp, 1m)\n| project timestamp, value, series = \"P95\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "sendPaymentOutcome Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"61dedafc2a92e81a0c7a58fd\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize total = count(), ko = countif(outcome != \"OK\") by bin(timestamp, 1m)\n| extend availability = 1 - todouble(ko) / todouble(total)\n| project timestamp, value = availability, series = \"Availability\"\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "sendPaymentOutcome Fault Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"61dedafc2a92e81a0c7a58fd\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize count() by bin(timestamp, 1m), outcome\n| project timestamp, value = count_, series = outcome\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "sendPaymentOutcome Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"61dedafc2a92e81a0c7a58fd\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=avg(duration) by bin(timestamp, 1m)\n| project timestamp, value, series = \"Avg\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    },
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"61dedafc2a92e81a0c7a58fd\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=percentile(duration, 95) by bin(timestamp, 1m)\n| project timestamp, value, series = \"P95\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "sendPaymentOutcomeV2 Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63c559672a92e811a8f33a01\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize total = count(), ko = countif(outcome != \"OK\") by bin(timestamp, 1m)\n| extend availability = 1 - todouble(ko) / todouble(total)\n| project timestamp, value = availability, series = \"Availability\"\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "sendPaymentOutcomeV2 Fault Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"63c559672a92e811a8f33a01\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize count() by bin(timestamp, 1m), outcome\n| project timestamp, value = count_, series = outcome\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "sendPaymentOutcomeV2 Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63c559672a92e811a8f33a01\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=avg(duration) by bin(timestamp, 1m)\n| project timestamp, value, series = \"Avg\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    },
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"63c559672a92e811a8f33a01\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=percentile(duration, 95) by bin(timestamp, 1m)\n| project timestamp, value, series = \"P95\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "verificaBollettino Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"61dedafc2a92e81a0c7a58fe\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize total = count(), ko = countif(outcome != \"OK\") by bin(timestamp, 1m)\n| extend availability = 1 - todouble(ko) / todouble(total)\n| project timestamp, value = availability, series = \"Availability\"\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "verificaBollettino Fault Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"61dedafc2a92e81a0c7a58fe\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize count() by bin(timestamp, 1m), outcome\n| project timestamp, value = count_, series = outcome\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "verificaBollettino Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"61dedafc2a92e81a0c7a58fe\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=avg(duration) by bin(timestamp, 1m)\n| project timestamp, value, series = \"Avg\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    },
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"61dedafc2a92e81a0c7a58fe\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=percentile(duration, 95) by bin(timestamp, 1m)\n| project timestamp, value, series = \"P95\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "verifyPaymentNotice Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"61dedafc2a92e81a0c7a58fb\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize total = count(), ko = countif(outcome != \"OK\") by bin(timestamp, 1m)\n| extend availability = 1 - todouble(ko) / todouble(total)\n| project timestamp, value = availability, series = \"Availability\"\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "verifyPaymentNotice Fault Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\ndependencies\n| extend operationId = tostring(split(operation_Name, \" - \")[1])\n| where operationId in (\"61dedafc2a92e81a0c7a58fb\")\n| extend faultCode = tostring(customDimensions.faultCode)\n| extend outcome = iif(resultCode == \"200\" and isempty(faultCode), \"OK\", iif(isempty(faultCode), tostring(resultCode), faultCode))\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize count() by bin(timestamp, 1m), outcome\n| project timestamp, value = count_, series = outcome\n",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "verifyPaymentNotice Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"61dedafc2a92e81a0c7a58fb\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=avg(duration) by bin(timestamp, 1m)\n| project timestamp, value, series = \"Avg\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    },
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "timeColumn": "timestamp",
      "query": "let instanceRaw = \"${Instance}\";\nlet instanceSelected = case(instanceRaw == \"Nexi Oracle\", \"NDP003PROD\", instanceRaw == \"Nexi Postgres\", \"NDP004PROD\", instanceRaw == \"PagoPA Postgres\", \"NDP001PROD\", \"No filter\");\nrequests\n| where operation_Name contains \"61dedafc2a92e81a0c7a58fb\"\n| project timestamp, operation_Id\n| join kind=inner (dependencies | project operation_Id, duration, target) on operation_Id\n| extend backend = case (target startswith \"https://weuprod.nodo.internal.platform.pagopa.it\", \"NDP001PROD\", target startswith \"https://10.79.20.34\", \"NDP003PROD\", target startswith \"https://10.79.20.25\", \"NDP004PROD\", \"Unknown\")\n| where iif(instanceSelected == \"No filter\", true, backend == instanceSelected)\n| summarize value=percentile(duration, 95) by bin(timestamp, 1m)\n| project timestamp, value, series = \"P95\"",
      "resources": [
       "/subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/Microsoft.Insights/components/pagopa-p-appinsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  }
 ]
}