name: Suspend NODO Cron job triggered by Azure Alert

on:
  repository_dispatch:
    types: [suspend-job-alert]
    inputs:
      environment:
        required: true
        description: 'The name of the environment where run the suspend job'
        type: string
      resource_group:
        description: 'Resource Group for AKS'
        required: true
        type: string
      cluster_name:
        description: 'AKS Cluster Name'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: 'The name of the environment where run the suspend job'
        type: string
      resource_group:
        description: 'Resource Group for AKS'
        required: true
        type: string
      cluster_name:
        description: 'AKS Cluster Name'
        required: true
        type: string


permissions:
  id-token: write
  contents: read

jobs:
  alertJob:
    environment: ${{ inputs.environment }}
    runs-on: [ self-hosted-job, "${{ inputs.environment }}" ]
    steps:
      - name: Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Install kubelogin
        run: |
          curl -LO https://github.com/Azure/kubelogin/releases/latest/download/kubelogin-linux-amd64.zip
          unzip kubelogin-linux-amd64.zip
          sudo mv bin/linux_amd64/kubelogin /usr/local/bin
          kubelogin --version

      - name: Get K8s context
        uses: azure/aks-set-context@4edaee69f820359371ee8bc85189ac03a21d3a58 # v3
        with:
          resource-group: ${{ inputs.resource_group }}
          cluster-name: ${{ inputs.cluster_name }}
          admin: 'false'
          use-kubelogin: 'true'

      - name: Get pods
        run: kubectl get pods -A -o wide
